### ISSUE TITLE
[BUG] Modules attached by default and can't be cleared.

### ISSUE THREAD

**Issue by Aberro** [ShadowTheAge/yafc#100]
After adding (inaccessible) recipe, it has productivity modules attached, which can't be cleared other than by module customization.
Latest page in attached project, named "test", mods used: all Pyanodon mods.
[project.zip](https://github.com/ShadowTheAge/yafc/files/6063891/project.zip)

**Comment by ShadowTheAge** [comment]
Fixed in 0.5.5 pre-release
