### ISSUE TITLE
[BUG] Recipes not showing localised name for multi product recipes

### ISSUE THREAD

**Issue by KiwiHawk** [ShadowTheAge/yafc#102]
YAFC 0.5.5

Some recipes names aren't showing correctly. The examples that I saw in YAFC that aren't working correctly have multiple products. It should be using the recipe's main_product (if defined) to get the localisation.

![image](https://user-images.githubusercontent.com/59639/110097317-bfa20480-7e03-11eb-8103-7650b1edcc3a.png)

**Comment by ShadowTheAge** [comment]
Fixed in the next release

**Comment by ShadowTheAge** [comment]
The release have been published https://github.com/ShadowTheAge/yafc/releases/tag/v0.5.6
Feel free to reopen the issue if the problem still exists
