### ISSUE TITLE
[BUG] Item tooltips not showing rich text

### ISSUE THREAD

**Issue by KiwiHawk** [ShadowTheAge/yafc#103]
YAFC 0.5.5

Angel's refining adds images to the tool tips for their ores. Should these show up in YAFC?

![image](https://user-images.githubusercontent.com/59639/110097876-671f3700-7e04-11eb-9c0b-c58f7b253109.png)

![image](https://user-images.githubusercontent.com/59639/110098161-bebda280-7e04-11eb-8b6b-1cb9c3c4060d.png)

**Comment by ShadowTheAge** [comment]
I use SDL text rendering and it doesn't support rich text. Even simple things like bold.
I can remove icons however.

**Comment by ShadowTheAge** [comment]
Somewhat fixed in the next release (tags are removed, \n also replaced with proper newline)

**Comment by ShadowTheAge** [comment]
The release have been published https://github.com/ShadowTheAge/yafc/releases/tag/v0.5.6
