### ISSUE TITLE
[BUG] fuel usage and speed

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#105]
- Be sure that you are using the latest version of YAFC  yes
- Please note that YAFC is my personal project and I can't promise any support!
- Specify the YAFC version

- Specify as much info as possible.
- If your bug is related to some mods, attach new game save file so I can sync mods to yours.
- If your bug is related to your .yafc project (for example errors in calculations), attach your .yafc file

in  py mods glassworks and other fluid fueled buildings have a max fluid usage rate of 600/s  but this is not implemented in YAFC 
so those buildings sometimes have an effective energy cap so a max speed cap for some fuels

**Comment by ShadowTheAge** [comment]
I have refactored energy calculations, now it should better handle edge cases, but it may also contain new bugs

Can you please build YAFC from the master version and confirm that it now works as intended, and also check old cases if possible (like burner-generators wit efficiency)?

**Comment by ShadowTheAge** [comment]
The release have been published https://github.com/ShadowTheAge/yafc/releases/tag/v0.5.6
Feel free to reopen the issue if the problem still exists
