### ISSUE TITLE
[BUG]  Double calculation of burning efficiency for energy

### ISSUE THREAD

**Issue by snowTH** [ShadowTheAge/yafc#106]
YAFC seems to apply the efficiency penalty of electricity generation twice.

For example, when using py's combustion turbine mk1, which has 42% efficiency, YAFC calculates the generated energy as 0.42 times the actual ingame generation (12.7 MW vs 5.34 MW for fluid at 520 degrees).

YAFC v0.5.5.0 shows 5.34MW for 1 turbine:
![YAFC](https://puu.sh/HuLkf/7ea788c6df.png)

While ingame I get up to 12.7MW per turbine:
![Ingame](https://puu.sh/HuLgD/478d986e3c.png)

This is a savefile to sync mods to if needed.
[SaveFile](https://github.com/ShadowTheAge/yafc/files/6249284/bugreportYAFC.zip)

**Comment by ShadowTheAge** [comment]
I have ended up refactoring the whole energy calculation code as I found other edge cases that was not handled properly.

**Comment by snowTH** [comment]
I tested the latest commit and it's fixed.
