### ISSUE TITLE
[Feature request] Total production sheet cost (Electricity)

### ISSUE THREAD

**Issue by DRouve** [ShadowTheAge/yafc#107]
Is there any way to calculate total cost of current production sheet?
For example, currently playing Pymods, I'm trying to calculate which electricity production recipes is cheaper in raw materials:
- Moss -> Biomass + Hydrogen -> Combustion Fuel -> Combustion turbine
or
- Moss -> Biomass -> Boiler -> Steam

So I want to see what production for 1MW is cheaper in raw materials like iron plates, steel etc. (YAFC cost, which is shown in japanese yen)

**Comment by ShadowTheAge** [comment]
Set production goal (desired product) in electricity (1MW for example)

**Comment by ShadowTheAge** [comment]
Or do you mean building costs? For building costs, in shopping list press "decompose"

**Comment by DRouve** [comment]
Sorry, can't find this "decompose"
![yafc](https://user-images.githubusercontent.com/59864935/114865433-e2f4a200-9dfa-11eb-9c8a-cb8ebb1b89e8.png)

What I would like to see is how much YAFC thinks 1MW of electricity would cost in "YAFC cost / yens" depending on current production sheet, considering used buildings and recipes

**Comment by DRouve** [comment]
Found it:
![yafc2](https://user-images.githubusercontent.com/59864935/114869182-60baac80-9dff-11eb-8a06-c901c453f8e1.png)
Yes, I guess this will do, thank you!
