### ISSUE TITLE
[Feature request] Nuclear reactor efficiency customization

### ISSUE THREAD

**Issue by Saklad5** [ShadowTheAge/yafc#109]
Right now, nuclear reactors are assumed to operate in a 2x2 configuration, each generating 120MW of power.

I understand this is the most common configuration, but I would prefer the ability to specify alternate configurations. I see three alternative improvements that could be made, of varying degrees of difficulty.

1. Allow a custom MW value to be specified for each instance of the recipe. For instance, if someone has a 3x2 layout, they would put 800 MW. If someone has a 3x3 layout, they would put 1320 MW.
2. Assume a double-row layout, and treat the power output as `160(n-1)` MW where `n` is the number of reactors (this formula is on the Factorio wiki).
3. Allow the dimensions to be specified for each instance of the recipe (2x2, 2x3, 3x3, etc.) and calculate it directly.

I think option 1 is the simplest, though option 2 has the benefit of not adding any UI elements.

I assume any such change would apply to things like Space Exploration’s antimatter reactor as well.

**Comment by ShadowTheAge** [comment]
Option 3 would be the simplest actually. Option 2 is non-option because it makes the model non-linear.

**Comment by Saklad5** [comment]
For now, I’m just dealing with this by setting the number of heat exchangers explicitly. That makes the rate of uranium fuel cell usage inaccurate, of course, but I can understand just leaving it with the notice about the assumed layout.

**Comment by ShadowTheAge** [comment]
Added as global preference setting
Version is not ready yet, you can build yourself https://github.com/ShadowTheAge/yafc/blob/master/Docs/HowToBuild.md

**Comment by Saklad5** [comment]
Thanks! Does this global preference setting apply to every such recipe, or just the vanilla nuclear reactor one?

**Comment by ShadowTheAge** [comment]
Every such recipe, including cases when they give other bonuses than +100% per connection

**Comment by ShadowTheAge** [comment]
The release have been published https://github.com/ShadowTheAge/yafc/releases/tag/v0.5.6
Feel free to reopen the issue if the problem still exists
