### ISSUE TITLE
[BUG] Failure to recognize rocket launch as automatable

### ISSUE THREAD

**Issue by maxreader** [ShadowTheAge/yafc#114]
Greetings!

When using the full set of Angel's mods only, without Bob's, the program correctly recognizes that a satellite should return Gravitational Analyzers, but does not recognize that they are "crafted" in the rocket silo. When attempting to select the "satellite launched" recipe, it gives the following error: 
```
Object reference not set to an instance of an object.

   at YAFC.ProductionTableView.AddRecipe(ProductionTable table, Recipe recipe) in C:\projects\YAFC\YAFC\Workspace\ProductionTable\ProductionTableView.cs:line 44
   at YAFC.ProductionTableView.<>c__DisplayClass9_0.<<OpenProductDropdown>b__2>d.MoveNext() in C:\projects\YAFC\YAFC\Workspace\ProductionTable\ProductionTableView.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at YAFC.UI.Ui.ProcessAsyncCallbackQueue() in C:\projects\YAFC\YAFCui\Core\Ui.cs:line 223
```
with the result: 
![image](https://user-images.githubusercontent.com/60635199/116196991-c65d4180-a6f9-11eb-932e-be8f3fd58830.png)

Mods included: 
![image](https://user-images.githubusercontent.com/60635199/116196716-767e7a80-a6f9-11eb-9ed7-cae40f87f5cf.png)

**Comment by maxreader** [comment]
It appears it may be due to Angel's changing the rocket silo so that it does not have a fixed recipe:

https://github.com/Arch666Angel/mods/blob/master/angelsindustries/prototypes/overrides/components-base-entity-update/components-base-other-entities-update.lua#L164-L168

**Comment by ShadowTheAge** [comment]
I can't find the recipes that are on your screenshots using the mods that are on your other screenshot

I need new game save file for syncing mods, mod versions and mod settings.

**Comment by maxreader** [comment]
It is likely due to a difference in startup settings:
[Angels Planning.zip](https://github.com/ShadowTheAge/yafc/files/6387944/Angels.Planning.zip)

The only other mods included do not affect recipes (Factory Planner, Rate Calculator).

**Comment by ShadowTheAge** [comment]
Fixed for the next version
You can build it https://github.com/ShadowTheAge/yafc/blob/master/Docs/HowToBuild.md

**Comment by maxreader** [comment]
Awesome, thank you!

**Comment by ShadowTheAge** [comment]
The release have been published https://github.com/ShadowTheAge/yafc/releases/tag/v0.5.6
