### ISSUE TITLE
[Feature request] Create new production sheet shortcut button

### ISSUE THREAD

**Issue by wesdotcool** [ShadowTheAge/yafc#116]
In this "Add Production Recipe" tooltip there should be a button to create a new production sheet for that item. The production sheet should be titled with the item and item image and the item as the desired product.

![image](https://user-images.githubusercontent.com/246963/118379875-ccc13980-b592-11eb-83c9-a9c52137c5db.png)

**Comment by ShadowTheAge** [comment]
That menu is already too complex and sometimes can be higher than the screen but I like the idea, I'll think about it

**Comment by ShadowTheAge** [comment]
Added to the next version (0.5.7). Only shows when the product is not linked.

**Comment by wesdotcool** [comment]
I get an error when I try to extract the Windows zip file from the release page https://github.com/ShadowTheAge/yafc/releases/tag/v0.5.7.1

**Comment by ShadowTheAge** [comment]
Thats weird, I have changed the zip compression algorithm but it was extracting fine using default Windows extractor
Anyways, I have reuploaded the release with the old compression algorithm

**Comment by wesdotcool** [comment]
It's working now. That new production table button is slick!
