### ISSUE TITLE
Suggestion: Save path preferences

### ISSUE THREAD

**Issue by binarycow** [ShadowTheAge/yafc#12]
Suggestion:  Save the path preferences so that the user doesn't need to specify them each time they open the application.

**Comment by ShadowTheAge** [comment]
It should already be saved. What OS are you using?
Oh, it is saved only when you save the project, orr when you specify project start at the beginning.

Because different projects can have different paths.

**Comment by binarycow** [comment]
I think that once I specify the path to Factorio's data location, and my mods folder, it should remember those.  If I want to change it for a specific project (maybe I keep a seperate mods folder for each project), then I can change it.

I do see tho, that now that I have saved a project, it set those values by default.  But sometimes I just want to open it and run a few numbers - I don't need to save it.

Also, it should "discover" Steam installs.  AFAIK, the Steam version is a well-known path.  If Factorio is installed in those locations, it should auto-populate.  If not found, it can stay blank.  It's a pain to hunt down where Steam puts things.

**Comment by ShadowTheAge** [comment]
Steam installs path and games path can be changed and to find it you need to look in the registry and I really don't want to touch the registry in a cross-platfom app

I have added a check for a "super default" install location whick is Program Files(x86)/Steam/steamApps/common/Factorio/data

Also I have added that factorio/mod paths are saved for even an empty project path.
Thats all for the next release (0.4.3)
