### ISSUE TITLE
[Feature request] add support for entities to the data crawler

### ISSUE THREAD

**Issue by kingarthur91** [ShadowTheAge/yafc#121]
yafc supports mods having code to set specific things as unlocked at start based on what ive seen with seablock. as far as i can tell it doesn't yet support entities.

to give more specific information ive added a crashed ship assembler to spawn at the start with pymods and with pyalienlife its required to make science. it cant be crafted ever and while i can manually mark that assembler as accessible by default yafc believes its not available and nothing can be unlocked till you do. please and thank you.

**Comment by ShadowTheAge** [comment]
It should already work {"type"="Entity", "name"=...}

**Comment by kingarthur91** [comment]
ok no idea why i didnt get that to work before but it is now. got another issue though now. it looks like if i add `if data.data_crawler then
	data.script_enabled = {
	  {type = "entity", name = "crash-site-assembling-machine-1-repaired"}
	}
  end
` in pyhightech or `if data.data_crawler then
	data.script_enabled = {
	  {type = "entity", name = "tar-patch"}
	}
end` in pypetroleumhandling it does work but if both are there it seems to override the first with the second as pyph loads last and the crashed assembler is no longer enabled.

**Comment by ShadowTheAge** [comment]
You should add to that list if it is already there, the whole `data` is parsed at the end similar to other things

**Comment by kingarthur91** [comment]
ok idk why it didnt work before but everything is good now and i think we can close this and file it under i did a dumb.
