### ISSUE TITLE
[BUG] Page duplication does not duplicate links

### ISSUE THREAD

**Issue by DaleStan** [ShadowTheAge/yafc#126]
Using the latest YAFC (3eafb7), I created the page Original, and then used the "Duplicate page" tool to create a duplicate page. I renamed the page to "Duplicate", but did not otherwise modify it.

The duplicated page is missing the links that were present on the original page. I expected the duplicated page to show 1.5 Iron ore and 0.11 coal per second in its ingredients. Instead it shows 0.5 each iron plate and iron gear in its ingredients.
[Test.zip](https://github.com/ShadowTheAge/yafc/files/6780563/Test.zip)

As a workaround, I can export and import via the clipboard; that preserves the links and demonstrates the expected behavior.

**Comment by ShadowTheAge** [comment]
Fixed for the next version
If you want the fix now you can build it https://github.com/ShadowTheAge/yafc/blob/master/Docs/HowToBuild.md

**Comment by ShadowTheAge** [comment]
v0.5.8 with the fix has been published here https://github.com/ShadowTheAge/yafc/releases
Feel free to reopen the issue if needed
