### ISSUE TITLE
Suggestion:  Allow default assembler options

### ISSUE THREAD

**Issue by binarycow** [ShadowTheAge/yafc#13]
Suggestion:  Allow the user to specify the default assembler to use for all new recipes, instead of needing to click the player icon, and change to an assembler.

**Comment by ShadowTheAge** [comment]
It remembers your assembler choice and tries to use it for newly added recipes.
Problem is, mods sometimes have several dozens of assemblers

Also if you see player icon, that maybe means that should mean that better assemblers are inaccessible based on unlocked milestones

**Comment by ShadowTheAge** [comment]
I have found a bug that caused "character" to be auto-selected even if there are other crafters availible
I have also added a manu that allows to mass-set assemblers and fuels
There is also a system that remembers crafters/fuels/modules that you use
Fixed for the next release
