### ISSUE TITLE
[Feature request] Submit YAFC to Steam as a free game

### ISSUE THREAD

**Issue by l0rem1psum** [ShadowTheAge/yafc#147]
Would like to see how much time I have spent on YAFC. Also, I think people will be willing to pay for the submission fee :)

**Comment by ShadowTheAge** [comment]
I don't think it is a good idea. Doesn't add anything constructive, but adds additional hassles with releases and with complying to ever changing regulations.

You can add any app, including yafc, as a non-steam game in steam.
