### ISSUE TITLE
[BUG] Linux.zip data folder case sensitive

### ISSUE THREAD

**Issue by SuperTux88** [ShadowTheAge/yafc#15]
First thanks for providing a Linux build. But it doesn't work out of the box, it tries to access files from the data folder, but fails to find them, because it tries to access `data/`, but the folder in the `Linux.zip` is called `Data/` with an uppercase `D`, this is a problem because on Linux filesystems and file access are case sensitive, so it doesn't find the files and crashes with a segmentation fault. Renaming the folder to a lowercase `d` fixes the problem and YAFC starts successfully, but it should already be with a lowercase `d` in the zip file.

**Comment by ShadowTheAge** [comment]
Hmm, I have tested the build in Debian and it worked, but thanks, I'll look into!

**Comment by ShadowTheAge** [comment]
I have found what is left accessing "data", the remaining code accesses "Data". Will build fixed version tomorrow.

**Comment by ShadowTheAge** [comment]
Please check the v0.4.2 pre-release where it should be fixed

**Comment by SuperTux88** [comment]
Thanks, it's working now without manually changing the `Data` folder. I found another strange error, but I just created #22 for that, so I close this because it's fixed :+1:
