### ISSUE TITLE
Error with Space Exploration 0.3.x

### ISSUE THREAD

**Issue by billbo99** [ShadowTheAge/yafc#16]
Was trying this calculator with  Space Exploration 0.3.x and got the below error

![image](https://user-images.githubusercontent.com/17733206/82742173-899f0280-9d52-11ea-9e26-0fb0a466c8f2.png)

**Comment by ShadowTheAge** [comment]
Can you please provide all the mods you use? (Preferably in a zip archive).
If the size is too big: Unpack all mods, find *.png, delete, pack what is left back

**Comment by billbo99** [comment]
Its nearly 600mb .. I have uploaded the folder here .. https://we.tl/t-e6onbVf1UT
The link will last a week before it expires.

**Comment by ShadowTheAge** [comment]
Fixed for the next release
