### ISSUE TITLE
Not able to apply beacons / modules to miners

### ISSUE THREAD

**Issue by billbo99** [ShadowTheAge/yafc#17]
I do not appear to be able to assign modules to miners
![image](https://user-images.githubusercontent.com/17733206/82742952-33cf5800-9d5c-11ea-9fad-64ab811f634b.png)

I have even checked the box "Fill modules in miners"

![image](https://user-images.githubusercontent.com/17733206/82742962-55304400-9d5c-11ea-950f-4813ae46249b.png)

**Comment by ShadowTheAge** [comment]
Fixed for the next release
