### ISSUE TITLE
[Loading error] Robot Army mod

### ISSUE THREAD

**Issue by EnzoMartin** [ShadowTheAge/yafc#189]
- [x] Be sure that you are using the latest version of YAFC
- [x] Try to remove outdated and disabled mods from your mod folder. If that helps, you may still make a report but you need to attach the whole contents of your mod folder, ioncluding all outdated and disabled mods.
- [x] Please note that YAFC is my personal project and I can't promise any support!
- [x] Specify the YAFC version and Factorio version: Factorio `1.1.74 (build 60256, win64)` & YAFC `0.5.8`
- [x] While YAFC should work with mods down to Factorio 0.17 (and maybe even earlier), I actively support only latest stable and latest experimental versions.
- [x] Attach a new game save file so I can sync mods to yours.

Hi,

When loading in the [Robot Army mod](https://mods.factorio.com/mod/robotarmy), YAFC throws a critical error (can't seem to copy-paste errors from the YAFC window):

> Collection was modified; enumeration operation may not execute at System.Collections.Generic.List`1.Enumerator.MoveNextRare() at YAFC.Parser.FactorioDataDeserializer.CalculateMaps() in [C:\projects\YAFC\YAFCparser\Data\FactorioDataDeserializer_context.cs:line 253](https://github.com/ShadowTheAge/yafc/blob/master/YAFCparser/Data/FactorioDataDeserializer_Context.cs#L253)

Screenshot:
![image](https://user-images.githubusercontent.com/735558/210529027-f27297e5-c7dd-4353-b43a-c843e46c8614.png)

Error only happens when enabling that 1 mod, save file attached: [RobotArmyNew.zip](https://github.com/ShadowTheAge/yafc/files/10342996/RobotArmyNew.zip)

**Comment by DaleStan** [comment]
This is almost certainly a duplicate of #164. If you can't build YAFC, unzip the Robot Army mod and delete the lines in prototypes/item.lua that say `place_result = "",`

**Comment by EnzoMartin** [comment]
Thanks for the reply! I can build YAFC locally yeah, I'll try and delete the line you mention in the mod files 👍

**Comment by EnzoMartin** [comment]
Built locally and tested with the mod, I can confirm that the problem is resolved with commit 70d171c82015747d3df7b4b6e7628a5bd8db140c in `master` 👍👍
