### ISSUE TITLE
Suggestion: Set the number of factories, not the number of items

### ISSUE THREAD

**Issue by binarycow** [ShadowTheAge/yafc#20]
For example:

I have 10 chemical plants making plastic bars.  I want to know how many oil refineries I need to satisfy the requirements of those 10 chemical plants.  I need to know how much coal/second I need to satisfy the requirements.

**Comment by ShadowTheAge** [comment]
The number of factories can be recursive (for example when you are making solid fuel, and you include smelting that uses solid fuel) - not a best example as vanilla solid fuel doesn't require smelting but you get the point.

So it is not an easy feature (ie it is not just "take the number of factories and multiply by crafting speed/amount)

It will be nice to have, but not high priority considering it is not an easy update

**Comment by ShadowTheAge** [comment]
This is now a feature of a new 0.5.0 experimental update here https://github.com/ShadowTheAge/yafc/releases/tag/v0.5.0
