### ISSUE TITLE
[BUG].4.2 error on load

### ISSUE THREAD

**Issue by TokMor** [ShadowTheAge/yafc#21]
- Be sure that you are using the latest version of YAFC
- For compatibility-related bugs, please make sure that these mods are working in Factorio
- For compatibility-related bugs, try removing disabled mods
- Please note that YAFC is my personal project and I can't promise any support!

- specify the YAFC version: .4.2
- Factorio version (Versions below 0.17 are not supported!): 18.18
- your OS (If the bug is OS-specific, I can provide very limited support for mac/linux, sorry!) Windows 10
- Attach ALL of your mods, including mod-list.json and mod-settings.dat, zipped (upload to some file share hosting). To reduce file size you can delete all images/sounds from the mods
https://www.dropbox.com/sh/a6lwkzvq6fqafg0/AABg-cumUefE1A1-C1uaYXdPa?dl=0
![image](https://user-images.githubusercontent.com/28193512/82760985-46ca4280-9dc5-11ea-8699-a17c97828bd4.png)

**Comment by ShadowTheAge** [comment]
Fixed for the next release (0.4.3) tomorrow

**Comment by ShadowTheAge** [comment]
0.4.3 is released as a pre-release https://github.com/ShadowTheAge/yafc/releases/tag/v0.4.3
