### ISSUE TITLE
Bug - syntax errors - Mods that don't load so far and small suggestions

### ISSUE THREAD

**Issue by oreganobag** [ShadowTheAge/yafc#23]
Windows 10
Latest experimental verson of Factorio

Getting error:

Loading terminated with code LUA_ERRSYNTAX
[string "307 data.lua"]:1: unexpected symbol near char(239)

With these mods (they all seem to be mods that don't actually add items). Alongside these are Pyanodon's and a handful of other QOL mods that cause no issue: 

GhostPlacerExpress - https://mods.factorio.com/mod/GhostPlacerExpress
GUI Manager - https://mods.factorio.com/mod/guiManager

That's it so far. I'll let you know if I find others.

Also small feature suggestions: When I am loaded up in YAFC, and I just added a new mod in Factorio, an option to restart YAFC/rescan the mods would be great so I wouldn't have to close YAFC, go back and manually open YAFC myself. Maybe if it errors out, it can print out what mod caused the error and it can return back to the previous set of items/database/whatever (sorry, I'm not a developer, just a casual Factorio player) that did work.

**Comment by ShadowTheAge** [comment]
Well, YAFC wouldn't work if you don't load mods in Factorio at least once

The reloading is a bit of a problem - There is some static state that is populated during loading and cannot be easily reloaded (Problems with objects referencing items and recipes from before-reloading and like that). It is not impossible, just requires time and not a priority right now.

About your error: it is *syntax* error, ie lua file is not a valid lua file. Maybe some sort of invalid character in a file, or wrong encoding, or something like this. I'll take a look tomorrow.

**Comment by ShadowTheAge** [comment]
Fixed for the next release

**Comment by ShadowTheAge** [comment]
0.4.3 is released as a pre-release https://github.com/ShadowTheAge/yafc/releases/tag/v0.4.3
Please reopen if there are more issues
