### ISSUE TITLE
ideas (or questions ) and a few bugs

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#24]
1 ) is it possible to use mixed modules 
2) not sure if the mod makes a difference between steam at different temperatures
( playing py mods with the last version ) 
3) is there a way to resize the window? atm it is from the very top of my screen and ends somewhere under my screen
4) using pyAL modules creates a error (unsolvable but it was solvable before (i think it is a bug related to negative productivity values , those values don't count in the game and are there only to prevent use in beacons)
5)  not sure about price algorithm but sometimes it seems off

**Comment by ShadowTheAge** [comment]
1) Currently not, Modules are still in the "partial support" state, I don't want to add a lot of data (like specifying each module) to each recipe, but loks like I will have to
2) Temperature is partially supported. You should get a warning if tempratures don't match. But there is no (currently) separate links for different temperatures. (Also there is a bug at determining result temperature that will be fixed in 0.4.3)
3) The window is resizable, but it starts at its minimum size. I should add downscaling the whole UI if the monitor is too small.
4) Can you please send me your project (.yafc file)? I didn't know about negative productivity, should add a check for it.
5) Price algorithm works as following:
- It assigns a "logistics cost" to each recipe. This cost depends on the amount of ingredietns, products, time, ore rarity for mining recipes, and some other coefficients.
- It makes sure that for *each* recipe sum(products cost) <= sum (ingredients cost) + (logistics cost)
but otherwise tries to maximize each item cost, especially "important" ones such as science packs.
The cost works on all accessible recipes, even on those that are not availible with current milestones. I was thinking about having separate cost for current milestones only, but, as usual, time :)

So, for example there is a simple mining recipe (nothing) + (1.5 logistics cost) <= (? 1x result cost) -> result cost will be 1.5 if there are no recipes that makes it less, for example if there is an alternate recipe (noting) + (2 logistic cost) <= (? 2x result cost) for the same result, the result will start to cost 1.

**Comment by immortal-sniper1** [comment]
ok
4 ) is is a standard -1% for all plant/animal modules
how should i send that file ?
email discord drive

**Comment by immortal-sniper1** [comment]
ok that sorta explains why pomp water was considered bad

**Comment by immortal-sniper1** [comment]
btw , not sure how familiar u are with pyAL BUT:
in the case of farms/ranch calculator may say 1200 without any modules but that is false! 
there is a script that stops them if there is no plant/animal module in them , it is not that important since it is easy to spot HUGE farm counts and notice something is wrong , is there a way to set default modules like in hellmod?

**Comment by ShadowTheAge** [comment]
There is a "filler module" that can be set up in the settings

**Comment by immortal-sniper1** [comment]
``` just attach it here``` how?

**Comment by immortal-sniper1** [comment]
[project1.txt](https://github.com/ShadowTheAge/yafc/files/4676255/project1.txt)

renamed extension since file was not supported

**Comment by immortal-sniper1** [comment]
biomass from kical was the problem

**Comment by immortal-sniper1** [comment]
also if i update mods
day recipe x gets a X10 buff 
will a tab refresh automatically or do i need to press something?

**Comment by ShadowTheAge** [comment]
you need to restart YAFC
Additionally, if you enable, disable, add or remove mods, you need to run the pack at least once in Factorio.
Hot reloading is a possible addition, but it is not currently a priority.

**Comment by immortal-sniper1** [comment]
well it was for mod balance purposes so it is very little general use

**Comment by ShadowTheAge** [comment]
Yes, I was thinking about using YAFC to balance mods just yesterday. And i think that would be a cool use of the tool. So I have added a task (https://github.com/ShadowTheAge/yafc/issues/26) to implement hot-reloading

Still not immediate plans but maybe closer to the next weekends.

**Comment by immortal-sniper1** [comment]
btw also regarding build comparison and balance 
what about a buildings used in total in a tab?

**Comment by ShadowTheAge** [comment]
added https://github.com/ShadowTheAge/yafc/issues/30

**Comment by ShadowTheAge** [comment]
I have tried to load your model, but there are missing recipes that don't match my pY installation, so I would need all the mods, or at least those that adds the following:

creative-mod_free-fluid-u-30 (recipe)
boiler.electric-boiler-mk4
seaweed-mk04 (item)
moss-mk04 (item)

Also it would help if you point on an incorrect calculation (preferably with screenshot)

**Comment by ShadowTheAge** [comment]
And I have also added check for negative productivity, so there may be no problem left
Is this correct?
![image](https://user-images.githubusercontent.com/7020122/82834922-2f757d00-9ecb-11ea-8ffe-e76b087d59f4.png)

**Comment by ShadowTheAge** [comment]
Yeah, not counting -1% productivity would certainly ruin this case as there are exactly 100 modules :D

**Comment by ShadowTheAge** [comment]
0.4.3 is released as a pre-release https://github.com/ShadowTheAge/yafc/releases/tag/v0.4.3

**Comment by immortal-sniper1** [comment]
yes
i will test it 

creative-mod_free-fluid-u-30 (recipe)  ( creative mode , so they dont count)
boiler.electric-boiler-mk4   my mod https://mods.factorio.com/mod/electric_water_boiler
seaweed-mk04 (item)   it is in game but it has no recipe atm ( pyAL is still work in progress) 
moss-mk04 (item)   same

**Comment by ShadowTheAge** [comment]
Hmm, is it stable enough?
I have started new py playthrough with AL ("Now I can finally play the game") and I don't want to redo half of the base after 100h :D

I have also noticed that pyAL does a lot of logs (that account for probably half of its loading time)
Also I have found cheaty recipe that allows you to launch a rocket using basically water and 1 crafting building (some farm, don't remember name). I thought I wasn't accounting for something in YAFC (it showed that space science is cheap) but nope, it works in game, just ad satellite :)

BTW if you want to see mod logs (lua `log`) just launch YAFC from console like powershell (the GUI will still show as usual)

**Comment by ShadowTheAge** [comment]
Also if you are familiar with mods maybe you know:
py aluminium

prototype states it requires 100 coal-gas
YAFC thinks it requires 100 coal-gas
FNEI thinks it requires 100 coal-gas
Factorio shows it requires 10 coal-gas

I don't see anything in the prototype and on wiki that accounts for that 10x difference
Is it just hardcoded?

**Comment by immortal-sniper1** [comment]
auto-farm spauns plants not space science (another thing that hellmod cant math the right way)

regarding py aluminum i think  it is 10/ unit from a gut feeling but i am not sure

Hmm, is it stable enough?  it is 
BUT i am still balancing stuff tho unless you stream it every day you will not run into them on a new map

**Comment by ShadowTheAge** [comment]
I have started a new sandbox scenario, cheated auto-farm, completed 1 recipe (something from water/dirt), put a satellite there, clicked "launch" and took my "hard earned" 1k space science packs

10/unit is correct, the question is why it is 10 when prototype specifies 100. My current assumption is that factorio defines a "mining operation" as "10 ores mined", so I have to just hard-divide by 10

**Comment by immortal-sniper1** [comment]
maybe

**Comment by immortal-sniper1** [comment]
regarding the science cheat that is interesting

**Comment by immortal-sniper1** [comment]
found another bug

**Comment by immortal-sniper1** [comment]
when loading mods it does not prioritize folders over archives (game does that )
how i found this bug , i edited some stuff and it did not change after a few edits at all

**Comment by ShadowTheAge** [comment]
Fixed for the next release
As the bug is minor, I don't know when the next release is going to be published. But you can download sources (using git or zip), and run "build.bat" (you need to have .Net core installed for that)
Build result will appear in Build/Windows

**Comment by immortal-sniper1** [comment]
i have 3.1 or something
