### ISSUE TITLE
[BUG] Index out of range exception

### ISSUE THREAD

**Issue by binarycow** [ShadowTheAge/yafc#28]
Got an "Index out of range exception" when loading a project file.

It's possible this is mod related, but I think it is likely how YAFC references mods in a project file, not the mods themselves.  

**SEE EDIT**

Couple days ago:
-  I had an open save in Factorio (Steam version)
- I created a YAFC project file. 
- I pointed YAFC to my Steam/Factorio data folder, my mods folder
- I saved the project file

Today:
- I had a *different* save open in Factorio (Steam version)
- This save has different mods enabled, including new mods that I installed today.
- My mod-list.json file is different today, from when the YAFC project file was created (due to different mods being enabled)
- I open YAFC, and open the existing project file (from a couple of days ago)
- Error occurs.

I understand that I may need to sync my mods to the original save, or create a new project file, or else YAFC might not be able to function.  **However,** I feel that at a minimum, a better error should be surfaced.  Additionally, an index out of range shouldn't actually occur - array bounds should be checked prior to array access.... Which will let you surface an error message, rather than throwing an exception (with its overhead)

** Suggestion **

Not sure how you implement this stuff, but I recommend that the "current" mods list is cached in the project file.  When a project file is loaded, it doesn't reference the mod-list.json file - it uses the cached mods list.  There would be some functionality for the user to "update" the cached mods list (in the project file) with the mods that are currently enabled (i.e., in the mod-list.json file), if new mods were enabled.

i.e., I should be able to open a YAFC project file, even if I do not have that exact set of mods **enabled** at that time (but, they are still **installed**)

If you're not interested in doing this at this time, but you're not opposed, I may do a PR for this type of functionality.

** Also Note **

- Your about dialog from the welcome screen doesn't indicate the software version
- YAFC.exe and YAFC.dll don't have version information specified in the file metadata (Shows as the default of 1.0.0.0)... Suggest changing VS project properties to include a version number, that you increment every tagged release (maybe make it part of a CI/CD pipeline)
- Your exception dialog doesn't allow me to copy/paste, nor resize - so I was not able to get the entire stack trace in one image.

**EDIT:**

Tried creating a new project file.  Got the same error.  So, my theory on why the error occurred is wrong, but my suggestions still stand (unless you're already doing that, and I don't see it).

I will upload mod data (as requested in the template), and edit the issue to provide a link.

----------------------------------------

- Be sure that you are using the latest version of YAFC
- For compatibility-related bugs, please make sure that these mods are working in Factorio
- For compatibility-related bugs, try removing disabled mods
- Please note that YAFC is my personal project and I can't promise any support!

- specify the YAFC version: **Unknown.**  EXE file modified date is ‎Saturday, ‎May ‎23, ‎2020, ‏‎3:30:02 PM
- Factorio version (Versions below 0.17 are not supported!)  : **0.18.21**
- your OS (If the bug is OS-specific, I can provide very limited support for mac/linux, sorry!)  **Windows 10**
- Attach ALL of your mods, including mod-list.json and mod-settings.dat, zipped (upload to some file share hosting). To reduce file size you can delete all images/sounds from the mods

![image](https://user-images.githubusercontent.com/37249876/82829670-d6cdc200-9e81-11ea-9ece-7a532cb2aa3e.png)
![image](https://user-images.githubusercontent.com/37249876/82829584-9706da80-9e81-11ea-9529-60c8c2918193.png)

**Comment by ShadowTheAge** [comment]
Thanks for the report
YAFC reads mod-list.json to determine current active mods
I don't think caching mod list inside the project is a good idea, because this will produce "wtf" moments.

It is much better to use "--mod-directory" factorio command line argument so all your mod folders are separate
YAFC can even launch Factorio with the correct mod-directory, but it can't create mod directory

However, the error should be fixed ofc.

**Comment by binarycow** [comment]
How do you use `--mod-directory` when using the Steam version?

Are you suggesting that I would create a separate mod directory for each save game, and then launch factorio with the correct mod directory for each save?  That's a pain, when I can just use Factorio's built in "Sync Mods" UI to enable the mods that are set for that save.  One button, rather than managing a whole bunch of folders.

Perhaps YAFC can, instead of pointing at a mod directory, point at a save game... YAFC would load the save game, check the mods that the save uses, and then go to the common mod directory to retrieve only those mods.  This allows me to use YAFC for a different save game than the one currently running in Factorio.  

That would also allow me to use YAFC in a situation where yesterday, I was running a game in Factorio that had mods A, B, and C.  I closed Factorio.  The next day, I open YAFC, and want to plan for a game that uses mods D, E, and F.  Currently, I would either have to have separate mod directories (a pain to manage), or I would have to launch Factorio, click the "Sync Mods" button, close Factorio, then open YAFC.

**Comment by binarycow** [comment]
Mod directory: https://drive.google.com/open?id=1dLVMwV21mISM5lkgZvNUmdsJncJ6cCrY

**Comment by ShadowTheAge** [comment]
How I use --mod-directory:
Open steam->Factorio->Properties->Set launch options. Type `--mod-directory vanilla`.
Run factorio to play vanilla
If you want to play something else: replace `vanilla` with anything
You don't need to create any directories, Factorio will load with no mods by default and then you can add mods

Factorio save format is proprietary and I can't read mods from it.

Also YAFC needs not only mod-list, but also mod-settings which will be incorrect
I don't support scenario when you didn't launch Factorio with the correct mod combination before loading the project, and adding that support is not easy.

**Comment by binarycow** [comment]
As a fellow developer, I respect the fact that you're allowed to decide "I don't support that scenario" !

**Comment by ShadowTheAge** [comment]
The "index is out of range" is fixed for the next release, that pack is now loading
The fix will be in the version 0.4.3
I will add versions into assembly and about screens.

**Comment by ShadowTheAge** [comment]
There is also a (distant) plans to be able to create a "package" that contains everything from the mods, so you don't need to take 1.5gb mods folder with you (so you can use it intead of factorio+mods folders)
That would be an okay compromiss for your other issue

**Comment by ShadowTheAge** [comment]
The "index out of range" should be fixed, and "mod-package" is still not immediate plans, I am closing the issue.
