### ISSUE TITLE
Medium-priority feature:  Include a "Bug Report / Mod Export" tool

### ISSUE THREAD

**Issue by binarycow** [ShadowTheAge/yafc#29]
In your bug report issue template, you ask that we provide a .zip file containing our mods directory.  You suggest that we can reduce the file size by deleting images/sounds.

My .zip file is 1.6 GB.  In order for me to remove images/sounds, I would have to unzip each mod, search for all images/sounds (of every format that exists), delete those, then re-zip everything back.  I could script this.... But, it's easier for me to just upload the entire 1.6GB file.

In order to make it easier for you to get the mod folders for debugging, I suggest that you provide a separate tool that will do that process for me, and package it all together.

**Comment by ShadowTheAge** [comment]
There is a better way to sync mods now - using new game save file. So mod export tool no longer needed
Additionally, the amount of errors related to mod importing are low
