### ISSUE TITLE
[BUG] all automated farm recipes are wrong by 2-3 factors 

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#33]
read title

**Comment by ShadowTheAge** [comment]
I need more information

**Comment by immortal-sniper1** [comment]
ok

**Comment by immortal-sniper1** [comment]
all recipes in tha building(that is a roket silo in disguise) activate a script that makes a plant-ore patch behind it , that plat of ore is 23x23 and each recipe up vives a larger amount per unit

**Comment by immortal-sniper1** [comment]
so it is 23x23x[recipe_tier+some koefficient] per craft

**Comment by ShadowTheAge** [comment]
Sorry, I don't understand, what is "plant-ore patch" and how is it related to the recipe amount?
Also, YAFC can't take into account anything that is spawned by script, that is just impossible.

YAFC doesn't take into account the delay for "launching a rocket" when crafting inside a rocket silo, that may be fixed, but only partially.

**Comment by immortal-sniper1** [comment]
plant-ore patch  it is like a normal ore , but when you mine it you get a plant
it is like a normal field 
related to the recipe amount?
formula is 23x23x[recipe_tier+some coefficient depending on plant] per craft , while atm it is 
registered as 1

**Comment by immortal-sniper1** [comment]
plant-ore is like a field of plants that you harvest

**Comment by ShadowTheAge** [comment]
I will not hardcode something for stuff that are spawned from script.
There is an ability to add mod-specific fixes (as lua scripts) that can create a fake recipe with the correct ratios

Or you can just split production table:
Part one: Filling the "automated farm"
Part two: Minig and using the plant-ore

Adding "custom recipes" (addable by the user) is also possible, but is not now a priority.

**Comment by immortal-sniper1** [comment]
Or you can just split production table:
Part one: Filling the "automated farm"
Part two: Minig and using the plant-ore
hmm i will try that , not sure if recipes are in there , or mining in general since i didnt use it unlill now
i will return in 5 min to see if it worked

**Comment by immortal-sniper1** [comment]
found the mining

**Comment by immortal-sniper1** [comment]
it seems to work well in 3 tabs +a piece of paper so it is fine by me
btw is there a way to account for tech mining prod ?

**Comment by ShadowTheAge** [comment]
Yes, dropdown near "modules" header -> more settings

**Comment by immortal-sniper1** [comment]
thx i saw it now , but i cehnged it a few times and i saw no changes

**Comment by ShadowTheAge** [comment]
I have checked it now and it works, at least for normal ore
This is a per-tab setting, not per-project, I may change that later.

**Comment by immortal-sniper1** [comment]
i did look only in one tab and i also tested with copper
maybe there is a step i am missing

**Comment by ShadowTheAge** [comment]
Check the following:
- This is a mining recipe (ie not smelting), and the "crafter" is some sort of mining-drill
- Change "mining productivity setting"
- Observe that amount of miners required have changed

**Comment by immortal-sniper1** [comment]
i did restart now and co change 
i used vanilla ore and miner to begin with

**Comment by ShadowTheAge** [comment]
I now see that miners without modules don't use mining productivity, I'll fix that
But for the regular case, I have set stupidly high productivity bonus here
![image](https://user-images.githubusercontent.com/7020122/83006084-5db5a280-a01a-11ea-99eb-2737407c0fa8.png)

**Comment by immortal-sniper1** [comment]
i also used HUGE numbers but i saw no change in miner count , i must be doing something wrong
