### ISSUE TITLE
[BUG] "Select"-Button disabled in project file selection dialog

### ISSUE THREAD

**Issue by SuperTux88** [ShadowTheAge/yafc#35]
Latest version 0.4.4 on Linux (I already had this problem with last version 0.4.3, but wasn't sure if it was only a glitch, and didn't pay to much attention to it, but after a friend told me he had the same problem, I thought I'd create a bug report)

When opening a project file, after selecting the correct file the "Select" button is still grey and can't be clicked:

![image](https://user-images.githubusercontent.com/458548/83056623-0c2b0900-a056-11ea-87f8-90afd4e651ff.png)

If I change the file name manually (for example delete the last character of the file name, see below), it becomes active (and also stays active when selecting the same or another file again), so it looks like selecting a file just doesn't trigger the change from inactive to active, only activity in the input field directly changes the state of the button)

![image](https://user-images.githubusercontent.com/458548/83056778-41cff200-a056-11ea-9f6c-a0dba8652a6a.png)

(And a side-question: The order of files/folders in the file selector is more or less random (at least I couldn't find an order, it's neither alphabetical nor it's ordered by the modification timestamp), so if a folder contains a lot of files/folders it really hard to find the correct one. I can work around this by manually enter the paths and you don't need to choose files that often (mostly only at the beginning), so it isn't that big of a deal, but sorting everything alphabetically would make a lot more sense.)

**Comment by ShadowTheAge** [comment]
Fixed for the next release
The file order was the order that OS returned files. It was sorted naturally on windows. I have added additional sort.

**Comment by SuperTux88** [comment]
Thanks for the fast fix :heart: (and I thought it's maybe a difference with the file API and it's maybe automatically sorted on Windows)

I built the current git master and both issues are fixed, so I'm closing this.
