### ISSUE TITLE
[BUG] Some Icons are missing

### ISSUE THREAD

**Issue by SuperTux88** [ShadowTheAge/yafc#37]
- Linux, latest unreleased master build
- Still factorio 0.18.26 with seablock mods, since not all mods are compatible with 0.18.27 yet

While testing the fix for #35 and #36, with the latest master version, I noticed that some Icons are missing:
![image](https://user-images.githubusercontent.com/458548/83064931-e821f480-a062-11ea-976d-6525a951e135.png)

I then built my own 0.4.4, where are icons are back again, so it's not my build that is broken. If I build one commit after 0.4.4 (https://github.com/ShadowTheAge/yafc/commit/f62aa3b580d79a07eaa33fb100ba7b090b75d28d), it's already broken, and since that commit does something with icon sizes, it has probably something to do with that (maybe some icons have no size and it sets it to 0, because the missing icons have a tiny pixel where there should be an icon)

Here is the same screenshot with 0.4.4 (so it looks like it's mostly the fluids and gases from angels mods (angels refining and angels petrochem)):

![image](https://user-images.githubusercontent.com/458548/83065517-e86ebf80-a063-11ea-9cd3-942315b1c46a.png)

Let me know if you need more infos, or if you can reproduce it without it.

**Comment by ShadowTheAge** [comment]
Yes, I have accidentally introduced this regression when experimenting with rendering icons at higher resolution. Fixed.

**Comment by SuperTux88** [comment]
Yes, I can confirm, icons are back :partying_face:
