### ISSUE TITLE
[BUG] Changing desired products amount doesn't work with numpad enter

### ISSUE THREAD

**Issue by SuperTux88** [ShadowTheAge/yafc#38]
Linux, latest version (well actually latest master at the moment, but was also with 0.4.4)

When changing the amount of the desired products, I need to confirm the new number with return (the big one on the main keyboard). When entering the new number on the numpad, it would be really convenient if it would work with the numpad enter key as well.

**Comment by ShadowTheAge** [comment]
You can also confirm by deselecting the field :)
Done, but note that I have squashed all these one-line fixes

**Comment by SuperTux88** [comment]
> You can also confirm by deselecting the field :)

Oh, I didn't notice this. But it's just muscle memory to hit numpad enter after entering a number ;)

> Done

Thanks, works :+1: 

> but note that I have squashed all these one-line fixes

You usually shouldn't force push to master (but it's your repo, so do whatever you want ;) and I'm maybe the only one who has cloned it and it wasn't a problem for me to reset my local copy since I know git pretty well).

And I personally like one commit per change with a clear commit message what was changed and why (and if available a link to the issue number it fixes) much more than one big commit with "Fixes" with a lot of changes in it. It's probably not a big problem yet, but it can help a lot when you want to understand why a line exists in the future (when you don't remember everything anymore), because it maybe makes no sense, but with a good commit message when you added/changed it, it maybe makes sense or you know that it can be removed now because that issue doesn't exist anymore.
