### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#39]
add a exit button , atm i can only close it using task manger  
also what about loading another file without closing the program (or rather said it closes the open one and opens the other one directly without loading the data from mod folder again )

**Comment by immortal-sniper1** [comment]
also the soil sorting recipe is producing organic matter not biomass (there was a update file that turned all organic matter making recipes into biomass) so there are probably all like this

**Comment by immortal-sniper1** [comment]
just noticed there is also a correct duplicate

**Comment by ShadowTheAge** [comment]
Exit button - just close the window
It may ask you if you have unsaved changes, but either answer, or press close again

Loading another file without closing a program is a good idea, but I will probably do it together with  https://github.com/ShadowTheAge/yafc/issues/26

About the mod recipe, so, does the problem exist?
If mods are changing, recipes in previously created projects may become missing or disabled, that is unavoidable.

**Comment by immortal-sniper1** [comment]
well that recipe is there but it is disabled ( i noticed a bit late the faded icon )

and i saw no close icon or X , it might be something related to the fact that is automatically sizes itself a bit over my screen size 
i never saw the top or bottom of the window

**Comment by ShadowTheAge** [comment]
You can use alt+f4 then to close the window
Downscaling windows to fit smaller screens will be in the next release

**Comment by immortal-sniper1** [comment]
ok 
alt+f4 is not as safe as task manger since i might accidentaly close something else

**Comment by ShadowTheAge** [comment]
I have published a pre-release 0.4.6 containing features:
- Mod reloading (via returning to the 'Welcome' screen)
- Open another project without reloading mods
- UI downscaling on a smaller screens
- 'Shopping list' displaying summary entities and modules required (under the "Entity" dropdown)

This release might be unstable.

**Comment by immortal-sniper1** [comment]
![image](https://user-images.githubusercontent.com/38986383/83333774-f95d4200-a2aa-11ea-8ef3-51a450527240.png)

**Comment by ShadowTheAge** [comment]
Does it work in Factorio? The exact version you are using with YAFC.
Factorio have changed a bunch of prototypes in its latest version, that broke mods

If yes, I need all the mods and exact factorio version, just screenshot of a in-mod error is not enough.

**Comment by immortal-sniper1** [comment]
last one

**Comment by immortal-sniper1** [comment]
{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "Actual_Craft_Time",
      "enabled": true
    },
    
    {
      "name": "BigStorageTank",
      "enabled": true
    },
    
    {
      "name": "BlueprintFlipAndTurn",
      "enabled": true
    },
    
    {
      "name": "Bottleneck",
      "enabled": true
    },
    
    {
      "name": "creative-mod",
      "enabled": true
    },
    
    {
      "name": "deadlock-beltboxes-loaders",
      "enabled": true
    },
    
    {
      "name": "DeadlocksStackingForPyanadon",
      "enabled": true
    },
    
    {
      "name": "DeleteEmptyChunks",
      "enabled": true
    },
    
    {
      "name": "EditorExtensions",
      "enabled": false
    },
    
    {
      "name": "electric_water_boiler",
      "enabled": true
    },
    
    {
      "name": "factoryplanner",
      "enabled": true
    },
    
    {
      "name": "fast_trans",
      "enabled": true
    },
    
    {
      "name": "ffff",
      "enabled": true
    },
    
    {
      "name": "flib",
      "enabled": true
    },
    
    {
      "name": "FNEI",
      "enabled": true
    },
    
    {
      "name": "giga_power",
      "enabled": true
    },
    
    {
      "name": "helmod",
      "enabled": true
    },
    
    {
      "name": "Infinizoom",
      "enabled": true
    },
    
    {
      "name": "LogisticTrainNetwork",
      "enabled": true
    },
    
    {
      "name": "MaxRateCalculator",
      "enabled": true
    },
    
    {
      "name": "OpteraLib",
      "enabled": true
    },
    
    {
      "name": "ore-erase",
      "enabled": true
    },
    
    {
      "name": "power_management_kit",
      "enabled": true
    },
    
    {
      "name": "pyalienlife",
      "enabled": true
    },
    
    {
      "name": "pyalienlifegraphics",
      "enabled": true
    },
    
    {
      "name": "pyalienlifegraphics2",
      "enabled": true
    },
    
    {
      "name": "pyalienlifegraphics3",
      "enabled": true
    },
    
    {
      "name": "pycoalprocessing",
      "enabled": true
    },
    
    {
      "name": "pycoalprocessinggraphics",
      "enabled": true
    },
    
    {
      "name": "pyfusionenergy",
      "enabled": true
    },
    
    {
      "name": "pyfusionenergygraphics",
      "enabled": true
    },
    
    {
      "name": "pyhightech",
      "enabled": true
    },
    
    {
      "name": "pyhightechgraphics",
      "enabled": true
    },
    
    {
      "name": "pyindustry",
      "enabled": true
    },
    
    {
      "name": "pypetroleumhandling",
      "enabled": true
    },
    
    {
      "name": "pypetroleumhandlinggraphics",
      "enabled": true
    },
    
    {
      "name": "pyrawores",
      "enabled": true
    },
    
    {
      "name": "pyraworesgraphics",
      "enabled": true
    },
    
    {
      "name": "qol_research",
      "enabled": true
    },
    
    {
      "name": "railloader",
      "enabled": true
    },
    
    {
      "name": "RaiLuaLib",
      "enabled": true
    },
    
    {
      "name": "Repair_Turret",
      "enabled": true
    },
    
    {
      "name": "SmallInlineStorageTank",
      "enabled": true
    },
    
    {
      "name": "Squeak Through",
      "enabled": true
    },
    
    {
      "name": "stdlib",
      "enabled": true
    },
    
    {
      "name": "Tapeline",
      "enabled": true
    },
    
    {
      "name": "Texugo_TA-miners",
      "enabled": true
    },
    
    {
      "name": "train-pubsub",
      "enabled": true
    },
    
    {
      "name": "train_tech",
      "enabled": true
    },
    
    {
      "name": "TSM-outpost-builder",
      "enabled": true
    },
    
    {
      "name": "UltimateBelts",
      "enabled": true
    },
    
    {
      "name": "Waterfill_v17",
      "enabled": true
    },
    
    {
      "name": "Wh40k_Armoury",
      "enabled": false
    },
    
    {
      "name": "what-is-it-really-used-for",
      "enabled": true
    }
  ]
}

**Comment by immortal-sniper1** [comment]
factorio .28  and for some reason .json files are not supported by github for direct upload

**Comment by ShadowTheAge** [comment]
I need all the mods, not just the mod list.
That includes disabled mods
This is a version-related problem and mod-info.json does not contain versions

**Comment by ShadowTheAge** [comment]
I am also seing that creative_mod was updated just a few days ago, with the changes to that exact line of code that are in the error screenshot. Was this mod really working in latest Factorio?

**Comment by immortal-sniper1** [comment]
all in the list are the last version

**Comment by immortal-sniper1** [comment]
yes creative_mod works atm ( i moved from here and there with that kind of mod often anyway )
it is really nice for testing in py since often you have a lot of loops and when it comes to fluids it is great for breaking and restarting testing

**Comment by ShadowTheAge** [comment]
creative mod latest version does not contain the code that is in the error screenshot
Latest version of creative mod does not have this error

**Comment by immortal-sniper1** [comment]
[creative-mod_1.4.2.zip](https://github.com/ShadowTheAge/yafc/files/4708074/creative-mod_1.4.2.zip)
