### ISSUE TITLE
[Feature Request] Duplicate production sheet

### ISSUE THREAD

**Issue by SuperTux88** [ShadowTheAge/yafc#41]
Sometimes I want to compare different possible recipes to create the same thing (often it's only a part of a production line that I want to replace with a second possible recipe). For that it would be useful to just duplicate an existing production sheet, where I then can replace one part with something else and then compare everything with the original (does it use less power, less input or less factories). At the moment I can either create a second production sheet from scratch (which can be a lot of clicks if it's 80% the same as the other but I only want to replace a part of it), or save the file and do the change in a second save (and then I need to switch between the files to compare them). So both workarounds are not really optimal (and just switching between two or even three tabs would be much better).

**Comment by ShadowTheAge** [comment]
Accepted as a future feature.
By the way, save files are simple json and you can duplicate there as a workaround. Just give the copy different guid.

**Comment by SuperTux88** [comment]
Yeah, I've also already done this to combine productions from two different files into one, but it's also not really optimal and the first time I messed up the guids (because I didn't know about that yet) and I also didn't know if I may accidentally break something else (but I took a backup before I manually edited the file), but I didn't get errors when loading the file, so I guess it worked.

**Comment by ShadowTheAge** [comment]
Page duplication have been pushed (not in any release still)

**Comment by SuperTux88** [comment]
Thanks, works as expected! :+1:
