### ISSUE TITLE
[BUG] Production sheets automatically hidden when creating new ones

### ISSUE THREAD

**Issue by SuperTux88** [ShadowTheAge/yafc#43]
Linux, latest release 0.4.6 or master build

Ok, I don't know if it's really a bug, but for me it's at least unwanted behavior. I have 8 production sheets open, when I create another one (or use the duplicate feature, it doesn't matter), it automatically hides the one at the end. But there is more than twice as much space on my screen to open more tabs, so that can't be the reason to hide tabs. When I then unhide the just hidden production sheet again, it just hides the next one at the end, but I want them all visible (at least as long as there is space on my screen).

Is this a hard limit or doesn't it try to use the complete window width? The open tabs are more or less the same with as the with of the table in a sheet, so I don't know if it just doesn't use the full window width?

**Comment by ShadowTheAge** [comment]
When I was doing tabs there was no horizontal scroll functionality implemented at that moment, so I added a hard cap to avoid "lost" tabs. I'll look at it.

**Comment by ShadowTheAge** [comment]
In the next version:
- Amount of non-hidden tabs no longer capped
- Tab bar can be scrolled
- If you have hidden pages *or* tab bar doesn't fit all pages, a new menu appears (that replaces old "Hidden pages" menu) that contains all the pages.

**Comment by ShadowTheAge** [comment]
0.4.7 is published

**Comment by SuperTux88** [comment]
Oh, sorry, I actually tested this yesterday night before I went to bed, then was sidetracked because I got an error that the rocket is inaccessible now (probably because I updated my mods) and then decided to go to bed and forgot to comment here that the tabs work as wanted now.

I also tested the released version now and that works too. :+1:

**Comment by ShadowTheAge** [comment]
There was a slight change in accessibility analysis.
Previously the line "false" (as string) in `recipe.enabled` was interpreted as true (the default value) but now it is interpreted like false because the recipe was actually disabled in game (YAFC was thinking that disabled recipe is enabled)

**Comment by SuperTux88** [comment]
I have angels+bobs (through seablock), and I think I found the cause, but I don't really understand why it happens. I know I need to enable some initial items (which I did, and they are still enabled), but now something that was working before now is disabled (I updated angels yesterday, so it didn't come witht he 0.4.7 update, the warning was also already with the 0.4.6).

So ingame I have this research:
![image](https://user-images.githubusercontent.com/458548/83558337-2ad84680-a513-11ea-8a61-e630a6db205b.png)

In YAFC it shows like this now: 
![image](https://user-images.githubusercontent.com/458548/83558414-4e02f600-a513-11ea-9cfe-6a67156d6808.png)

Some of the recipes that should be unlocked with it, are still disabled, but not all of them? :thinking: I could probably manually enable all of them, but something feels off here. It also shows it needs yellow science instead of green (well, on a second look it requires the correct science packs, only the icons are wrong, the yellow icon has the name of the red pack, the red science has the name of the green science ... and on prerequisites it shows the correct icons :shrug: ). The Ferrous Anode Sludge is the reason why the rocket isn't accessible.

I can create a new issue for that and send you the mods if you want to have a look at it?

**Comment by ShadowTheAge** [comment]
If the recipe is disabled, then it means it is locked by something else (like a disabled ingredient) and you should investigate further

**Comment by SuperTux88** [comment]
OK, I found the reason ... When I manually enabled this, everything is working again (this is where the Ferrous Anode Sludge is made)
![image](https://user-images.githubusercontent.com/458548/83559755-670ca680-a515-11ea-800e-ae0841e6d930.png)

But the worse part is, this recipe is actually disabled ingame :scream: And I don't find a research which should unlock it ... luckily I have already built a factory which builds these from before the upgrade (and it looks like while the recipe is still set in the factory, it can still produce them), so I have them, I just should never delete this factory ...

And about the colors, I have no idea why it's wrong at some places, and I didn't remember if it was correct before I updated the mods, I didn't pay attention to them and I also don't mind if they're wrong ... (and it looks like this is the only problem with YAFC, the other things are a problem with the mods or my upgraded savegame ...)

**Comment by ShadowTheAge** [comment]
Well, does the missing recipe mean that the rocket is actually unlaunchable in this modpack?

**Comment by SuperTux88** [comment]
Yes, it looks like the rocket is really unreachable with the current versions of the mods (the official modpack is with older mod versions and with older factorio, so I'm actually playing an unsupported combination at the moment, but I wanted the new UI/icons and the faster saving of the newer factorio version, so I also needed to upgrade all the broken mods ... and I finally got mod versions that launch again without throwing an error, but it looks like there is still something broken and YAFC analyzed the mods correctly and the warning is actually true)
