### ISSUE TITLE
[BUG] well sorta

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#44]
when making nuclear cells for power i tried to limit the amount of spent ones vs ore but i could not

maybe when you make nuclear fuel cells add a option to get same amount of spent cells ? so something like a input limiter 

also when doing solar power math does it account for day night cycle or not ?

**Comment by immortal-sniper1** [comment]
and when doing steam power it tries to use steam from a power house (and that will never work since it is just hot water) 60C

**Comment by ShadowTheAge** [comment]
> when doing solar power math does it account for day night cycle or not
It should have a hard-coded coefficient for Nauvis (70% power output)

> and when doing steam power it tries to use steam from a power house (and that will never work since it is just hot water) 60C
If you have fluids with different temperatures and this matters for you you should have a nested table

> maybe when you make nuclear fuel cells add a option to get same amount of spent cells ? so something like a input limiter
Currently I don't understand, can you explain with more details?

**Comment by immortal-sniper1** [comment]
yes```Currently I don't understand, can you explain with more details?```

lets say i want to make and use 1/s nuclear cells 
after they are spent i will get 1/s used cells (1:1)

so when i plan U chain i want to keep into mind the 1/s spent as a input , since i can get U-238 from it and that reduces a lot the U ore needed

**Comment by immortal-sniper1** [comment]
```If you have fluids with different temperatures and this matters for you, you should have a nested table (limiting the temperature you need)
Having separate links with different temperatures is techincally possible but I don't see how to make a good-enough gui for that.```  
i didnt make the mods anyway i simply made the power in another tab but this problem might(99%sure it will) appear in some other recipes

**Comment by ShadowTheAge** [comment]
Well, there is sort-of possible now as YAFC knows about (and calculates) the used-up uranium cells, but there is nowhere to display it.
However if you make a loop with cells, it will be calculated
Here is an example:
![image](https://user-images.githubusercontent.com/7020122/83790735-51c48300-a6a1-11ea-8361-3dfb4a5a3d71.png)

I want to add an option to specify the amount of crafting buildings eventually. That would help with this too.

**Comment by ShadowTheAge** [comment]
In addition, you can specify negative amount of desired products and this would work as "external input" (YAFC will try to consume that input if possible)

**Comment by immortal-sniper1** [comment]
ok that would work ok for me , since i am only intending to use the U waste from REE chain to make some power

**Comment by immortal-sniper1** [comment]
interesting 
so that is a way to effectively use it as a input priority , equivalent of hellmod

**Comment by ShadowTheAge** [comment]
there is no prioryty but there is a way to say "please consume 1/s of something" the same way as saying "please produce 1/s of something"

**Comment by immortal-sniper1** [comment]
btw is there a way to" force " a recipe even tho it is useless ? 

situation : i need fo void some fuel and i want to overproduce a useless recipe until all the fuel is used

**Comment by immortal-sniper1** [comment]
also does nuclear power math include neighbor bonus ?

**Comment by ShadowTheAge** [comment]
nuclear power does not include neighbour bonus as it doesn't know your configuration.
YAFC tries to match production with consumption exactly, and this includes using up things
You need to allow overproduction for the result of the useless recipe.

**Comment by immortal-sniper1** [comment]
btw , i didn't notice last night , how do you enable dark mode or change the background color ?

**Comment by ShadowTheAge** [comment]
It is the next release feature

**Comment by immortal-sniper1** [comment]
nice

**Comment by ShadowTheAge** [comment]
If you want it now you can build YAFC from sources. Download sources and run "build.bat". (have .net core installed)

**Comment by immortal-sniper1** [comment]
i dont have core installed and dark mode is not that important atm

**Comment by immortal-sniper1** [comment]
i just noticed that YAFC now load from folders with priority , GREAT
