### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dexmark5** [ShadowTheAge/yafc#45]
It is the  creative mod  that i am using 
![Untitled](https://user-images.githubusercontent.com/66437747/83795022-c0e8aa00-a696-11ea-8bce-565c6ba0c664.png)

**Comment by ShadowTheAge** [comment]
I think "creative mod" have been updated to fix this error (that mod was broken in Factorio as well)

**Comment by ShadowTheAge** [comment]
There is also a possibility that you have both versions (old and new) of Creative Mode installed and YAFC selects the wrong one. If this is the case, this would be fixed in the next update (0.4.8)

**Comment by ShadowTheAge** [comment]
Please check if the problem still exists in the 0.4.8 release https://github.com/ShadowTheAge/yafc/releases

**Comment by ShadowTheAge** [comment]
I hope this is fixed but if not feel free to reopen it
