### ISSUE TITLE
[Feature Request] Import/Export of production sheets

### ISSUE THREAD

**Issue by SuperTux88** [ShadowTheAge/yafc#50]
I know that the production sheets are just JSON and I could copy them out of the file. But if I just want to share a production sheet I planned with a friend, it would be really convenient to just export the JSON of only that sheet to copy-paste (similar like exporting a blueprint in factorio) and then similar on his end, an import feature to create a production sheet based on the copied JSON.

This is only a nice to have feature, there are already other ways to share planned sheets (I could also just send him my file and he could switch between his and my file), but it would make things easier :)

**Comment by ShadowTheAge** [comment]
This is a planned feature, yes

**Comment by ShadowTheAge** [comment]
v0.4.9 have been released with this feature

**Comment by SuperTux88** [comment]
Thanks :heart:
