### ISSUE TITLE
[BUG] Error while loading data folder

### ISSUE THREAD

**Issue by Crucerio** [ShadowTheAge/yafc#51]
![image](https://user-images.githubusercontent.com/12720569/83954315-73ac3a00-a848-11ea-85ab-b51ccad6fe29.png)

Factorio Version 0.18.30
Version 0.4.7
Linux
No mods in use

The only configured path is the data path in the factorio folder in steamapps and also when using the standalone factorio version.

**Comment by ShadowTheAge** [comment]
That's very strange. It is reporting nullref just after a null check. (Probably that means that memory is 
What version of .net core are you using?

**Comment by Crucerio** [comment]
I have the sdk version 3.1.300

**Comment by ShadowTheAge** [comment]
Well, I'll add a try-catch in icon rendering in 0.4.9 but if the memory is corrupt, that probably wouldn't help much.

**Comment by ShadowTheAge** [comment]
I have found a possible nullref in one of the adjacent lines, so, maybe the line number is not correct, and it will be fixed in the next release.

**Comment by ShadowTheAge** [comment]
v0.4.9 have been released, please check

**Comment by ShadowTheAge** [comment]
I hope this is fixed but if not feel free to reopen it
