### ISSUE TITLE
[BUG] tab name dissapears 

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#55]
v0.4.9 

name of the tabs suddenly disappeared from some of my tabs and in some it was displaying power usage instead of the name of the tab

BTW great job with new module&beacon system

**Comment by ShadowTheAge** [comment]
I think this is some sort of rare gpu texture corruption or very rare memory corruption issue. I haven't encountered it ever and I hope it is not repeating.
