### ISSUE TITLE
[BUG] Incorrect fuel usage for Pyanodon drillheads

### ISSUE THREAD

**Issue by TwentyEighty** [ShadowTheAge/yafc#56]
YAFC v0.4.9
0.18.32
Win10
pyfusionenergy

![image](https://user-images.githubusercontent.com/49283746/85217981-fadad100-b363-11ea-891f-88ad18af3a15.png)

Shows 45+ drill heads a second for mining 60/s molybdenum ore. Helmod shows ~0.71 a second which is correct. The number of mines listed is correct, just the fuel is wrong

**Comment by ShadowTheAge** [comment]
Fixed for the next release (0.4.10)

**Comment by ShadowTheAge** [comment]
v0.4.10 have been published with this fix

**Comment by TwentyEighty** [comment]
Confirmed! Thanks!
