### ISSUE TITLE
[BUG] Milestone Bug?

### ISSUE THREAD

**Issue by TwentyEighty** [ShadowTheAge/yafc#57]
v0.4.9
Factorio v0.18.32
Win10
Full PySuite, no other overhaul mods (Will provide mod list on request)

Appears to be a milestone bug. This is telling me blue science and I can't figure out why, I can do the whole chain

![image](https://user-images.githubusercontent.com/49283746/85232222-58eecf00-b3cb-11ea-9268-8dd43d702267.png)

Here's the relevant research:

![image](https://user-images.githubusercontent.com/49283746/85232255-994e4d00-b3cb-11ea-94f1-326585c60e9f.png)

**Comment by ShadowTheAge** [comment]
It is usually best to open "Dependency explorer" and go back from there to find milestone problems
I have tried on my py installation and got down to:
* "Jig concentrator" that is a blue science entity
* Because of "Electric engine unit"
* because of "electric engine" technology

**Comment by TwentyEighty** [comment]
Whoops you're completely right, sorry

**Comment by ShadowTheAge** [comment]
Well, that is why that feature exists in the first place :) And this is why it looks deeper than just at recipes and technologies.

**Comment by ShadowTheAge** [comment]
By the way, you can mark milestones as completed. This will remove milestone from the availible objects, and also YAFC will know what you have access to, and that will affect sorting, suggestions and some other stuff.
