### ISSUE TITLE
[BUG] Recursive Steam due to temperature

### ISSUE THREAD

**Issue by TwentyEighty** [ShadowTheAge/yafc#58]
- Be sure that you are using the latest version of YAFC
- For compatibility-related bugs, please make sure that these mods are working in Factorio
- For compatibility-related bugs, try removing disabled mods
- Please note that YAFC is my personal project and I can't promise any support!

- v0.4.10
- Latest experimental factorio
- Win10
- Mod files on request, full pyanodons suite

This recipe heats steam that is less than 500 degress to be 500 degrees for certain recipes, and give itself an unsolvable loop in YAFC.
![image](https://user-images.githubusercontent.com/49283746/86406816-cdeebe00-bc81-11ea-9b76-c8384d9ce5f6.png)

Similarly, understanding fluid temperature would also allow the correct recipes to show up here:
![image](https://user-images.githubusercontent.com/49283746/86406929-068e9780-bc82-11ea-9d1f-4651293d1cf6.png)

This recipe only accepts 500 degree steam, and the UI lets me choose from ANY steam producting recipe, including "waste" steam that is 60 degrees and useless.

Also, attaching temperatures to fluids would allow more accurate YAFC costs for things like pymods combustion mixture.

Anyway, no idea if this is possible or not, but thanks for reading.

**Comment by ShadowTheAge** [comment]
You can use YAFC for combustion mixtures as long as you have one fixed temperature. YAFC calculates fluid temperature but it is not part of the solution model.

One possible solution is to allow having multiple links for one type of resource and manually attaching links to inputs/outputs. This is totally fine for model solving purpose but is a gui problem. And it isn't currently possible to attach settings to "ports" (inputs or outputs of a recipe).

So, that is possible to solve but I don't know how to make it configurable and covering all cases (IE I don't want to implement a solution that covers only this single case)

I remember using "waste" steam for tin mining

**Comment by TwentyEighty** [comment]
One suggestion is to gather all the min and max values from the recipes when analyzing them, and break up the fluid into that many intervals. So for steam, in vanilla, you'd read the recipes that take min temp 165, and min temp 500, and you'd end up with 0-165 steam, 165-500 steam, and 500+ steam. And YAFC could treat those as three different fluids with three different values.

No idea if this is possible or not but it's one idea I've been thinking about. YAFC would end up with dozens of combustion fluids for py mods, but that's actually the case so I think it would be ok.

**Comment by ShadowTheAge** [comment]
well, splitting the fluids is not a problem. I can suggest even simpler splitting algorithm: Look at production table and take all unique temperature results.

The problem is merging back. What if you have a recipe that accepts both temperatures? How to determine which of the split fluids to link to?

And what if these different temperatures are more than two?

**Comment by TwentyEighty** [comment]
Closing this after the 0.5 release :) Thanks!
