### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#59]
yafc  4.9 
not sure why but while loading the mods the program ended up using 11-12GB RAM 
so i had to close it 
i am now updgrading to 4.10 to see f i still have that problem

**Comment by immortal-sniper1** [comment]
4.10 has the same problem

**Comment by ShadowTheAge** [comment]
Just please provide more information when opening bugs
I would close future issues if there are nothing in them to start investigating
First, the mod list
Second, when was the memory usage registered? What was you doing that caused memory spike?

**Comment by immortal-sniper1** [comment]
it turned out to be my mistake in editing the mod files
not sure how it broke but it is fixed
