### ISSUE TITLE
[BUG] Py AlienLife: Tuuphra recipes show zero for soil and blood meal

### ISSUE THREAD

**Issue by TwentyEighty** [ShadowTheAge/yafc#60]
v0.4.10
- Latest experimental Factorio
- Latest Win10
- Mod list on request. It's full Py suite including Pyanodons Alien Life

For some reason, these tuuphra recipes show zero for soil and bloodmeal inputs. I can't figure out why. It's only the soil and bloodmeal, and it's only these several Tuuphra recipes, from what I can tell.

![image](https://user-images.githubusercontent.com/49283746/86938486-797a9100-c10e-11ea-89a1-0a74da742268.png)

By comparison, here's helmod

![image](https://user-images.githubusercontent.com/49283746/86938639-a4fd7b80-c10e-11ea-8d0f-ff0c9f9a3839.png)

**Comment by ShadowTheAge** [comment]
the amount was string "20" instead of number 20, it is a parsing error. Fixed for the next version.

**Comment by ShadowTheAge** [comment]
Published v0.4.11 pre-release with this fix

**Comment by TwentyEighty** [comment]
Verified thanks!
