### ISSUE TITLE
Suggestion: Clarify what the YAFC analysis suggestion means

### ISSUE THREAD

**Issue by TwentyEighty** [ShadowTheAge/yafc#61]
Given this:

![image](https://user-images.githubusercontent.com/49283746/86938936-fe65aa80-c10e-11ea-876f-fa83c8e868a8.png)

Is this calculated using Tier 1 buildings? Or the latest tier available? Is there some hidden science goal that this number is based on?

**Comment by ShadowTheAge** [comment]
well, it is just an approximation. It is using buildings with the crafting speed of 1. 
What it means is that when simulating "late-game base that produces enough resources to do every non-infinite research", the amount of recipes required exceeded some threshold. This threshold depends on mods complexity (when you are playing more complex mods, it is okay when your base have overall smaller output)
It is not a goal, just an indication that the recipe is probably more important that "just have 1 building and consider it done"

**Comment by ShadowTheAge** [comment]
NEIE panel has recieved an UX update and now it displays building-hours instead
