### ISSUE TITLE
[SUGESTION] 

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#62]
i saw the shopping list
can you maybe add a building total like hellmod?
why: it is in order to compare different complex builds where calculating the building count takes a long time

**Comment by ShadowTheAge** [comment]
But shopping list _is_ a building total (if you don't press "decompose" button)

**Comment by immortal-sniper1** [comment]
second

more like this:
10 sail extractor
10 moss farms
45 hpf
13 DDC
7 composters
and i want to see 95 as a building total

**Comment by ShadowTheAge** [comment]
ok I'll add it the next release (but the date is currently uncertain)

**Comment by immortal-sniper1** [comment]
ok 
BTW



    Be sure that you are using the latest version of YAFC

    For compatibility-related bugs, please make sure that these mods are working in Factorio

    For compatibility-related bugs, try removing disabled mods

    Please note that YAFC is my personal project and I can't promise any support!

    v0.4.10

    Latest experimental factorio

    Win10

    Mod files on request, full pyanodons suite

i tried to make a hot air build but i noticed that the same fluid with different temperatures is counted as identical , and that makes math impossible for hot air builds since the temperature of fluids matters (you use hoat fluid to heat up things and when it cools you heat the fluid with combustion mixture)

**Comment by ShadowTheAge** [comment]
Yes, I know about this problem and would like to have to fixed but at the moment I don't have a good idea on how to do it :(

**Comment by immortal-sniper1** [comment]
no problem i ended up doing it by hand anyway and it is only 1 chain (until py adds another one )

**Comment by ShadowTheAge** [comment]
Fluids with temperature are now supported in the experimental release
