### ISSUE TITLE
[REQ] More granular shopping list

### ISSUE THREAD

**Issue by skofisk** [ShadowTheAge/yafc#63]
Shopping list is a nice tool, but when you have a massive list of recipes and buildings, only having the total is not that useful.
Having a separate shopping list for every step of the tree would be helpful.
I have made a mockup of this proposed feature, see attached image.

Example, full Circuit 2 build in PyAL, all in one tab. Split up into nested tables to make planning and building easier.
![shopping_proposal](https://user-images.githubusercontent.com/26026953/87851382-7777b580-c8f8-11ea-8ea4-d53fed2c79c8.png)

**Comment by ShadowTheAge** [comment]
I have added this to the next version but I don't know when it is going to be published (there are not enough features/fixes currently for a version)

You can build a version yourself if you have dotnet core installed, just run `build.bat`, nothing else is required.

**Comment by skofisk** [comment]
Built and tested, thanks :)
