### ISSUE TITLE
[BUG] Crash from KERNELBASE.dll on windows 7

### ISSUE THREAD

**Issue by Sopel97** [ShadowTheAge/yafc#65]
When launching a windows (or windowsfat) executable on windows 7 it crashes immediately from KERNELBASE.dll. The issue stems from usage of `SetProcessDpiAwareness` from `SHCore.dll` https://github.com/ShadowTheAge/yafc/blob/master/YAFCui/Core/Ui.cs#L26. Commenting lines 25 and 26 prevents the crash and the application works correctly.

**Comment by ShadowTheAge** [comment]
Hm, that function is only supported for newer version of windows. I should add a check in the next version.

That function makes YAFC gui better (sharper fonts, etc) for systems with several monitors with different DPI (I have such setup) that's why it is there.

**Comment by ShadowTheAge** [comment]
I have published 0.4.12 release and this should be fixed by catching exception.
Checking OS version weren't working properly in published release.
