### ISSUE TITLE
[BUG] Factorio Recipe Limitation

### ISSUE THREAD

**Issue by Aplyde** [ShadowTheAge/yafc#66]
Recipes can only be executed once every tick. This normally doesn't come into play with vanilla gameplay but I used YAFC to plan my FactorioExtended Plus Megabase. YAFC said I'd need 2.82 assemblers to make 424/s of inserters. Now the problem is that because of the game's limitation the 3 assemblers I had could only produce 180/s.

Also just a quick thank you for providing such a nice tool for free! It really helps a lot with modded playthroughs.

**Comment by ShadowTheAge** [comment]
Hi, do recipes always rounds up? IE 1.2 ticks per recipe becomes 2 ticks per recipe?

**Comment by Aplyde** [comment]
Did a few quick tests. 1.2 ticks skips executing the recipe every 6th tick. Funnily enough recipes which take less than 1 tick still save their progress and work with that saved progress even after the respective beacons are deconstructed but cant execute the recipe more than once per tick.

**Comment by ShadowTheAge** [comment]
So it is only a limit, not a rounding. I'll add the limit to the next version.

**Comment by Aplyde** [comment]
Ok did some more tests. The limitation apparently only applies when a machine doesn't use productivity modules. Tested with a recipe taking 1 second. At 75 crafting speed it produces 60/s. After inserting a productivity module (250%, had to use a cheat one cause recipe normally doesn't allow productivity) it produces 247.13/s (should be 210/s if crafting speed was limited at 60/s). Honestly not really sure how that comes together though. Only 210/s and 262.5/s would be plausible.

**Comment by ShadowTheAge** [comment]
So it looks like the main parts are affected by the limit while "extra" from productivity arent (60 + 75*2.5)
Then this is slightly problematic because future systems may have to assume productivity depends linearly on speed.
I have implemented like this by now, but I don't have your setup so I ask you to build it (download latest sources and run build.bat, have .Net core installed) and check the calculations

**Comment by Aplyde** [comment]
It's working now. Tested both with and without productivity and reflects in-game results. Thanks for the quick fix!

**Comment by ShadowTheAge** [comment]
Wait, does it mean that it gives you extra productivity for free?
You are spending ingredients for 60/s but getting extra products as if it was 75/s?
Or are you spending ingredients 75/s but getting 60/s output?

**Comment by Aplyde** [comment]
Oh I just noticed every recipe which is flagged with the production being limited has wrong input numbers. 
![Easiest example](https://user-images.githubusercontent.com/68964341/88842565-f49c0800-d1df-11ea-9e18-2376a63abcdd.PNG)

**Comment by ShadowTheAge** [comment]
Thats what I was worrying about the previous comment. Can you test for iron gears with and without productivity - how many gears are produced and how many iron is consumed

**Comment by Aplyde** [comment]
Ok so a fully beaconed assembler has 73.2 crafting speed and 136% productivity. It produces 259.45/s iron gears and consumes 120/s iron plates. So yeah you actually get quite a bit of productivity for free, as it takes the input only once per tick.

**Comment by ShadowTheAge** [comment]
So the numbers in 0.4.12 are actually correct

**Comment by Aplyde** [comment]
Yeah seems so. Should I continue using 0.4.12 or is it unstable?

**Comment by ShadowTheAge** [comment]
You can continue using it. There were only minor fixes - I don't think those break something.
