### ISSUE TITLE
[BUG] Incorrect 1/tick limiting of generators with >100% efficiency

### ISSUE THREAD

**Issue by Sopel97** [ShadowTheAge/yafc#68]
When a generator (for example combustion turbine mk3 from pycoalprocessing) has efficiency above 100% the calculation becomes incorrect and the user is informed that the rate was limited to 1/tick, which doesn't make sense for power generation recipes.

![obraz](https://user-images.githubusercontent.com/8037982/89465141-e450d380-d771-11ea-90ec-7913bdfba9ca.png)

**Comment by ShadowTheAge** [comment]
Thanks for quick issue, I have fixed it and updated release to 0.4.12.1
