### ISSUE TITLE
[BUG] Incorrect use of prod modules

### ISSUE THREAD

**Issue by TwentyEighty** [ShadowTheAge/yafc#70]
![image](https://user-images.githubusercontent.com/49283746/90044441-a553de00-dc9b-11ea-857b-d93af2cacdbc.png)

I can't actually use prod modules here in game. I suspect the recipe allows them but the building does not

**Comment by Sopel97** [comment]
Same goes for the atomizers.

Note that the prod modules don't get picked when using the automatic assignment, so I think this is correctly handled in at least one part of the code.

**Comment by ShadowTheAge** [comment]
Fixed for the next version
There are several ways to configure modules. In case that mismatching module somehow gets there it will be now ignored. And removed one of the ways to add mismatched modules

**Comment by ShadowTheAge** [comment]
I have published 0.5.1 and confirmed again that this issue should be fixed
