### ISSUE TITLE
[BUG] Critical Error on mod pack that loads in factorio 0.18.47

### ISSUE THREAD

**Issue by TokMor** [ShadowTheAge/yafc#71]
YAFC version 0.5.0
![image](https://user-images.githubusercontent.com/28193512/90170279-cd137680-dd6d-11ea-9732-bd0d9f9cc984.png)
Factorio version 0.18.47

mod collection https://www.dropbox.com/sh/a6lwkzvq6fqafg0/AABg-cumUefE1A1-C1uaYXdPa?dl=0

Please let me know if I can provide additional info to help. Thanks!

**Comment by ShadowTheAge** [comment]
Fixed for the next version (0.5.1)

However, this modpack has a lot of complicated localization that is not displaying correctly right now. More fixed required

**Comment by TokMor** [comment]
Thanks! I can deal with localization issues as long as the thing loads.

**Comment by ShadowTheAge** [comment]
I have fixed some localization issues
Also most of the items are inaccessible, probably need to mark "burner-omnitractor" or something like that as accessible (I'm not familiar with omnimatter)

Here is a private build as I am not ready to release 0.5.1 now
[Windows.zip](https://github.com/ShadowTheAge/yafc/files/5070988/Windows.zip)

**Comment by ShadowTheAge** [comment]
0.5.1 is now released
