### ISSUE TITLE
[BUG] [Russian] Accesibility issues with Pyanodons modpack after Factorio 1.0 release

### ISSUE THREAD

**Issue by insidio118** [ShadowTheAge/yafc#72]
Не уверен, разработчик из России или нет. Но попробую. В случае чего могу продублировать на Английском.

В кратце - после выхода Факторки 1.0 - YAFC перестал нормально работать с модпаком Пьянодона. А именно - сломался accesibility рецептов. Я конечно долго и муторно прокликал в dependencies все рецепты и всё теперь по идее работает. Но суть в том что в 0.18 экспериментальной версии этой проблемы не было. 

Возможно дело в Факторио 1.0, возможно в мелкой обнове одного из модов Пьянодона. Буду рад если это починят.

**Comment by ShadowTheAge** [comment]
Я сам играю в pyanodon (pyblock) и вроде бы проблем (кроме мелких связанных с новым роботом) не обнаружил. Кроме того я знаю что в дискорде pyanodon активно пользуются YAFC. Так что думаю что дело в конкретной комбинации модов.

Я обновил все py моды без pyblock и проблемы не вижу. Возможно ее пофиксили авторы модов.

1.0 сломал некоторое количество модов. Вполне возможно что какой то рецепт действительно поломался и большая часть py стала непроходимой - такие случаи уже бывали.

**Comment by insidio118** [comment]
Я играю не на Пайблоке. Единственный мод который возможно что-то сломал это Alien Biomes. Попробую выключить. Но дело в том, что если я щас попробую заново создать проект - то вероятно заново придется настраивать accesibility.

**Comment by insidio118** [comment]
Не работает вообще теперь

Ссылка на красноту https://i.gyazo.com/122a81a53d514c854a2c7e9110bda5a6.png

**Comment by insidio118** [comment]
На 0.50 запускается но с проблемой аналайзера.  https://i.gyazo.com/9224888487ea6719861bae984e9e3b4e.png

**Comment by ShadowTheAge** [comment]
Тогда нужны все можы или (если они все точно последней версии!) хотя бы их список

**Comment by insidio118** [comment]
Архив модов весит 2гб. Так что прикреплю просто модлист. 

[mod-list.zip](https://github.com/ShadowTheAge/yafc/files/5076589/mod-list.zip)

**Comment by ShadowTheAge** [comment]
судя по картинке - YAFC ну видит ни одной генерящейся руды кроме камня. Отсюда и все проблемы недоступности

**Comment by ShadowTheAge** [comment]
mod-list недостаточен к сожалению т.к. там нет версий. Подойдет сохранение новой игры.

**Comment by insidio118** [comment]
[YAFC Issue testing. new game.zip](https://github.com/ShadowTheAge/yafc/files/5076620/YAFC.Issue.testing.new.game.zip)

**Comment by insidio118** [comment]
Добавлю - неделей ранее я патчил пьянодон для совместимости с AAI Industry, там дубликаты в рецептах убирал. По итогу ААИ я отключил ибо он сильно имбовый для пьянодона. Но возможно это стало причиной последствий описанных выше?

**Comment by ShadowTheAge** [comment]
Эти квадраты не похожи на стандартный спавн ресурсов. Какой то мод их меняет.
Если этот мод меняет их методом "отключить автомпавн и спавнить скриптом" то дело в этом.
![image](https://user-images.githubusercontent.com/7020122/90284221-52844d00-de7a-11ea-934f-9d20e5d35b9f.png)

**Comment by insidio118** [comment]
Это улучшенный спавнер ресурсов Py. Он галочкой включается при запуске карты. Это Пьянодоновская опция

**Comment by insidio118** [comment]
Так не хочется ничего вручную помечать, у тебя ведь работает нормально всё. Почему у меня не так? :)

**Comment by ShadowTheAge** [comment]
Да, дело в ней
YAFC не может никак учитывать то что происходит скриптами в процессе работы игры. К примеру Angels удаляет спавн стандартного железа. YAFC понимает что стандартное железо копать нельзя именно по тому что у него отключена генерация на карте

Нужно пометить только руду по идее, ее не так много.

**Comment by insidio118** [comment]
Вот блин. То есть всякие изменения в спавне ресурсов сторонними модами - это табу? Ибо я седня пробовал и с Resoruse Spawner Overhaul - то же самое было.

**Comment by ShadowTheAge** [comment]
Нужно просто у десятка объектов поставить достижимость. Специально для таких случаев делалась возможность.

Одни моды спавнят ресурсы сами, другие запускают рецепты сами, и т.п. - мне как-то необходимо знать что достижимо а что нет. Иначе будет советовать кривые рецепты, цепочки и т.п.

К примеру в bobs mods есть электролизатор. Но если добавить еще и angels то он убирает электролизатор боба, и добавляет свой. Электролизатор боба читерский по сравнению с ангелским, если не учитывать достижимость то YAFC будет совсем неправильно считать стоимости и сложности объектов.

**Comment by ShadowTheAge** [comment]
кроме достижимости есть еще и milestones - к примеру титановую скалу можно копать только на синей науке. Но понять это можно только если пройти по всей цепочке производства и понять что без синей науки никак. А для этого нужно более-менее точно знать достижимость

**Comment by insidio118** [comment]
С системой доступности и майлстоунов я давно знаком. Это столкнулся с этим багом и вылезли проблемы с цепочками производства на ранних этапах игры (до красной банки в Ру в частности).

**Comment by ShadowTheAge** [comment]
Я впрочем добавлю себе заметку про спавн руды. Как-нибудь сделаю на старте окно которое показываент что "так и так, руды недоступны, точно?" - но это точно не приоритет. Пометить доступными объекты - 5 минут, пройти пианодон - 500 часов :D

**Comment by ShadowTheAge** [comment]
в той сохранке которую ты скинул достаточно выключить галку про руду и все заработает. По крайней мере у меня так

есть еще один нюанс правда. Если есть большая куча выключенных модов, а также модов которые включены но их зависимости выключены, то может быть я где-то не совсем точно определяю список модов которые надо грузить. Я правда давно с таким не сталкивался, думал что все такое починил.

**Comment by insidio118** [comment]
Отбой. Да. Даже после переустановки модов остались сохранения настроек. Выключил - заработало. Мистика какая-то. Но в целом проблему нашли. Если в будущем добавят опцию чека спавна руд из других модов или источников - было бы круто. Спасибо за оперативность)

**Comment by insidio118** [comment]
Серыми остались лишь некоторые рецепты войда вещей. (сжигания). И вещей которые почему-то есть в моде но нет в игре. Но думаю это не критично.

**Comment by insidio118** [comment]
> Я впрочем добавлю себе заметку про спавн руды. Как-нибудь сделаю на старте окно которое показываент что "так и так, руды недоступны, точно?" - но это точно не приоритет. Пометить доступными объекты - 5 минут, пройти пианодон - 500 часов :D

Я решил проблему лайфхаком. Можешь не заморачиваться. В общем я попросту скопировал моды в отдельную папку и указал их как мод фолдер в YAFC. А сам факторку запустил с модами на генерацию ресурсов как мне удобно. По итогу всё работает.
