### ISSUE TITLE
[BUG] Can't load/create project

### ISSUE THREAD

**Issue by Aplyde** [ShadowTheAge/yafc#76]
![YAFC_Error](https://user-images.githubusercontent.com/68964341/91581539-d6483a00-e94e-11ea-8db5-1aa004723bd4.PNG)

Happens with 0.5.0 and 0.4.12. I recently switched hardware and changed the Factorio folder location so maybe that's it?

**Comment by ShadowTheAge** [comment]
The error shows that archive is compressed with a compression algoritm that is not supported by the microsoft c# library I am using for unzipping.

As a workaround you can extract all mods into folders, or you can do it one by one to find such mod (It would be nice if you upload that mod for future investigation)

Switching an unzipping library is not a simple task and I would prefer to not do it, but maybe there are workarounds.

**Comment by Aplyde** [comment]
Ok it seems I somehow had a weird version of https://mods.factorio.com/mod/Yuoki installed. I had a version 1.0.01 installed which the game didn't recognize as well and isn't on the mod portal. Anyways, thanks for the help!
