### ISSUE TITLE
Suggestion: Block recipe types from YAFC calculations

### ISSUE THREAD

**Issue by whizzball1** [ShadowTheAge/yafc#79]
- I am using YAFC 0.5.0
- I am using Factorio 1.0
- I am using Windows

I have added the mod "Transport Drones" to my Pyanodon instance to allow for large scale transportation. To accomplish its work, it creates recipes that use one "transport drone" and a fuel to make "60k * 3" of every single item in the game. YAFC says this only costs Y3.6K, so it always makes the transport drone recipe the least expensive recipe.

This isn't an urgent issue since I can still review the Y costs of the non-transport drone items. But it would be great if I could tell YAFC not to use any recipes from the transport drones mod, or more accurately not to consider any recipes that use a particular building, so that I don't have to worry about this!

An example of the problem, for the production of raw fiber.
![image](https://user-images.githubusercontent.com/5273157/91678985-db96b780-eafb-11ea-8ae8-3f5fc41f8455.png)

Thank you for making this program!

**Comment by ShadowTheAge** [comment]
You can open "dependency explorer" and mark any recipe as inaccessible. You can also mark any building as inaccessible and this will make any recipe that require that building inaccessible.

**Comment by ShadowTheAge** [comment]
I hope you have resolved your situation, if not feel free to reopen the issue or reach me on Pyanodon discord.
