### ISSUE TITLE
Chaning number of beacons PER entity ..

### ISSUE THREAD

**Issue by billbo99** [ShadowTheAge/yafc#80]
How do I make the refinery can get max coverage from 20 beacons and whereas the chem plants the best they can get is 12.

Is there a way to override the number of beacons per row?

![refinery](https://cdn.discordapp.com/attachments/504895044088758273/753206177038598174/unknown.png)

**Comment by ShadowTheAge** [comment]
yes, click on it (or maybe on modules, i don't remember) and click "customize modules"

**Comment by billbo99** [comment]
OK, found it,  didn't realise I needed to enter 40 to get it to add 20 beacons to the machine

![override](https://cdn.discordapp.com/attachments/599613851524399134/753238563541352519/unknown.png)

**Comment by ShadowTheAge** [comment]
yes, it is noted there. Because people wanted to customize individual modules
