### ISSUE TITLE
Missing production modules

### ISSUE THREAD

**Issue by jcart** [ShadowTheAge/yafc#81]
I cannot seem to get production modules to show in the list.

For context, I have a mod that enables productivity modules on intermediate products, but I don't think it's related since the modules do not show on machines (i.e., drills) and recipes that would support it.

When viewing the custom module listing, I am further not able to see productivity there either. 

![missing-production](https://user-images.githubusercontent.com/1815438/93833066-93c00780-fc45-11ea-85cb-27a7340d5bf5.PNG)

Version I have should be latest, 0.5.1.

Thanks for the program, a lot of potential and looking forward to seeing it grow.

**Comment by ShadowTheAge** [comment]
Hi, I need all the mods, or at least all the mods besides Py if Py is latest and unchanged.

**Comment by jcart** [comment]
Thanks for quick response!

Appologies, I'm not able to attach json files. I've included the modlist.json below.

It's quite a long list so if there is anything obvious that is problematic I can try different permutations. 
`
{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "alien-biomes",
      "enabled": true
    },
    
    {
      "name": "angelsaddons-pressuretanks",
      "enabled": true
    },
    
    {
      "name": "angelsaddons-warehouses",
      "enabled": true
    },

    {
      "name": "AutoTrainDepot",
      "enabled": true
    },
    
    {
      "name": "blueprint_flip_and_turn",
      "enabled": true
    },

    {
      "name": "bobinserters",
      "enabled": true
    },
    
    {
      "name": "boblibrary",
      "enabled": true
    },

    {
      "name": "bobmining",
      "enabled": true
    },

    {
      "name": "Bottleneck",
      "enabled": true
    },
    
    {
      "name": "BuggisNuclearBots",
      "enabled": true
    },
    
    {
      "name": "ChunkyChunks",
      "enabled": true
    },
    
    {
      "name": "CJsInfiniteOres",
      "enabled": true
    },

    {
      "name": "creative-mod",
      "enabled": true
    },
    
    {
      "name": "deadlock-beltboxes-loaders",
      "enabled": true
    },
    
    {
      "name": "deadlock-compressed-titanium",
      "enabled": true
    },
    
    {
      "name": "deadlock-integrations",
      "enabled": true
    },
    
    {
      "name": "DeadlockCrating",
      "enabled": true
    },
    
    {
      "name": "DeadlockCrating_Integrations",
      "enabled": true
    },
    
    {
      "name": "DeadlocksStackingForPyanadon",
      "enabled": true
    },
    
    {
      "name": "deep-storage-unit",
      "enabled": true
    },
    
    {
      "name": "DragonIndustries",
      "enabled": true
    },
    
    {
      "name": "EvenMoreTextPlates",
      "enabled": true
    },
    
    {
      "name": "FactorioExtended-Plus-Core",
      "enabled": true
    },
    
    {
      "name": "factoryplanner",
      "enabled": true
    },
    
    {
      "name": "Flare Stack",
      "enabled": true
    },
    
    {
      "name": "flib",
      "enabled": true
    },
    
    {
      "name": "fluid-memory-storage",
      "enabled": true
    },
    
    {
      "name": "informatron",
      "enabled": true
    },
    
    {
      "name": "jetpack",
      "enabled": true
    },
    
    {
      "name": "Kythbloods_Stacked_Mining",
      "enabled": true
    },
    
    {
      "name": "LightedPolesPlus",
      "enabled": true
    },
    
    {
      "name": "logistic-memory-units",
      "enabled": true
    },
    
    {
      "name": "LogisticTrainNetwork",
      "enabled": true
    },
    
    {
      "name": "LSlib",
      "enabled": true
    },
    
    {
      "name": "LtnManager",
      "enabled": true
    },
    
    {
      "name": "nixie-tubes",
      "enabled": true
    },
    
    {
      "name": "omnilib",
      "enabled": true
    },

    {
      "name": "OpteraLib",
      "enabled": true
    },
    
    {
      "name": "OreEraser",
      "enabled": true
    },
    
    {
      "name": "PickerAtheneum",
      "enabled": true
    },
    
    {
      "name": "PickerDollies",
      "enabled": true
    },
    
    {
      "name": "Placeables",
      "enabled": true
    },

    {
      "name": "productive_py",
      "enabled": true
    },
    
    {
      "name": "PumpAnywhere",
      "enabled": true
    },
    
    {
      "name": "pY-electric-pole-tweak",
      "enabled": true
    },
    
    {
      "name": "pyalienlife",
      "enabled": true
    },
    
    {
      "name": "pyalienlifegraphics",
      "enabled": true
    },
    
    {
      "name": "pyalienlifegraphics2",
      "enabled": true
    },
    
    {
      "name": "pyalienlifegraphics3",
      "enabled": true
    },
    
    {
      "name": "pycoalprocessing",
      "enabled": true
    },
    
    {
      "name": "pycoalprocessinggraphics",
      "enabled": true
    },
    
    {
      "name": "pyfusionenergy",
      "enabled": true
    },
    
    {
      "name": "pyfusionenergygraphics",
      "enabled": true
    },
    
    {
      "name": "pyhightech",
      "enabled": true
    },
    
    {
      "name": "pyhightechgraphics",
      "enabled": true
    },
    
    {
      "name": "pyindustry",
      "enabled": true
    },
    
    {
      "name": "pypetroleumhandling",
      "enabled": true
    },
    
    {
      "name": "pypetroleumhandlinggraphics",
      "enabled": true
    },
    
    {
      "name": "pyrawores",
      "enabled": true
    },
    
    {
      "name": "pyraworesgraphics",
      "enabled": true
    },
    
    {
      "name": "QuickItemSearch",
      "enabled": true
    },
    
    {
      "name": "railloader",
      "enabled": true
    },
    
    {
      "name": "RecipeBook",
      "enabled": true
    },
    
    {
      "name": "recursive-blueprints",
      "enabled": true
    },
    
    {
      "name": "ReStack",
      "enabled": true
    },
    
    {
      "name": "rso-mod",
      "enabled": true
    },
    
    {
      "name": "SchallMachineScaling",
      "enabled": true
    },

    {
      "name": "Squeak Through",
      "enabled": true
    },
    
    {
      "name": "stdlib",
      "enabled": true
    },
    
    {
      "name": "Tapeline",
      "enabled": true
    },
    
    {
      "name": "textplates",
      "enabled": true
    },
    
    {
      "name": "themightygugi_longreach",
      "enabled": true
    },
    
    {
      "name": "TimeTools",
      "enabled": true
    },
    
    {
      "name": "Warehousing",
      "enabled": true
    },
    
    {
      "name": "Warehousing-Compression",
      "enabled": true
    }
  ]
}
`

**Comment by ShadowTheAge** [comment]
unfortunately mod-list isn't enough as it does not contain versions
I need either:
- archive with all mods besides py
or
- new game save file (save files contains all mods and versions and allow syncing)

**Comment by jcart** [comment]
I've cleaned up the mods that were previously disabled, and reinstalled others. 

Looks like it is working correctly, so I would assume it was likely one of the mods I had previously enabled causing a conflict? Honestly not sure since I didn't change much.

Regardless, thanks for help.

**Comment by ShadowTheAge** [comment]
well, if there was a case where modules exist in game but don't exist in YAFC that is still a bug
So I would still appreciate a save game with an empty ("new game") save if that reproduces
