### ISSUE TITLE
[BUG] Could not find a part of the path...

### ISSUE THREAD

**Issue by ModdedGamers** [ShadowTheAge/yafc#82]
- YAFC Version 0.5.2
- Factorio version 1.0.0
- macOS
- [Mods](https://ufile.io/yx2nt6nd)
![Error Screenshot](https://user-images.githubusercontent.com/35778371/98386647-717c2080-201e-11eb-97b7-7253552705ae.png)
When I try to reopen my project, I get this error. What can i do to fix it?

**Comment by ShadowTheAge** [comment]
It tries to open a file that is part of YAFC (ie it is not related to mods, etc)
Try launching YAFC so that target directory is equal to application directory
For example if you are launching from command line, make it so the "current directory" in the terminal is equal to YAFC app directory

**Comment by ModdedGamers** [comment]
That was it. Thanks so much!
