### ISSUE TITLE
MadClown's Nuclear: attempt to index local 'sounds' (a nil value) - when starting YAFC

### ISSUE THREAD

**Issue by RJFelix** [ShadowTheAge/yafc#84]
![Screenshot 2020-12-06 192922](https://user-images.githubusercontent.com/17805905/101306307-67099e00-37f9-11eb-894f-569ea7fbd6d9.png)

YAFC 0.5.3, Windows
Factorio 1.0

Removing all unused mods/mod versions fixed it. I had updated to 1.1 and downloaded updated mods, but there were incompatibilities so I downgraded back to 1.0, meaning I had 1.0 and 1.1 versions of many mods in the folder. I can zip up the mods folder as it was to reproduce this bug if you want.

**Comment by RJFelix** [comment]
Mod list: [mod-list.json.txt](https://github.com/ShadowTheAge/yafc/files/5650320/mod-list.json.txt)

**Comment by ShadowTheAge** [comment]
If the bug is related to having multiple incompatible mod versions then I think I need the whole folder
I'll try to load only compatible mod versions but it is not easy to reproduce the exact Factorio behaviour for such edge cases

**Comment by RJFelix** [comment]
Mod folder: https://mega.nz/file/hLIiSLpQ#FDzfDkTzfpdaue-pU9eW--p6Q0X0CCTivpjB9LNesmc

**Comment by ShadowTheAge** [comment]
This case is fixed for the next version (0.5.4) but I don't think all such cases could be handled properly

**Comment by ShadowTheAge** [comment]
v0.5.4 has been released as a pre-release. I am closing the issue now, if your problem is not solved feel free to reopen it.
