### ISSUE TITLE
[BUG] crash with return to start menu and attempting to load a project.

### ISSUE THREAD

**Issue by kingarthur91** [ShadowTheAge/yafc#85]
- 5.3.1
- 1.1.x (6?)
- win 7
- just pycoalprocessing and its dependents

it only crashes when i use the return to starting screen button. then attempt to load a project ive already loaded in the same active session. i can load other projects that i havent loaded yet just fine. completely closing and reopening yafc from the folder doesnt have any issues with any project this has happened with. 

![image](https://user-images.githubusercontent.com/29772132/102711259-2fcdcf00-4286-11eb-8433-81d355296c59.png)

**Comment by ShadowTheAge** [comment]
Unfortunately I wasn't able to reproduce, so more questions:
* Are there any changes between reloading the project? Does it work if there are none?
* Does it related to the project file (.yafc)? Does it reproduces on an empty project? If no, attach a project file.

**Comment by kingarthur91** [comment]
it doesnt seem to be project specific. got no error with an empty project. and i just loaded up the one i was using earlier for that crash report and its not doing it now. i cant seem to reproduce the issue at this time.

**Comment by ShadowTheAge** [comment]
Fixed for the next version (0.5.7)
