### ISSUE TITLE
There seems to be a change between version 0.5.1 and 0.5.3.1 that causes the dependency explorer to incorrectly identify certain recipes and items that should be disabled as available/unlockable instead.

### ISSUE THREAD

**Issue by ShadowTheAge** [ShadowTheAge/yafc#86]
There seems to be a change between version 0.5.1 and 0.5.3.1 that causes the dependency explorer to incorrectly identify certain recipes and items that should be disabled as available/unlockable instead.  

Example blank .yafc project: https://pastebin.com/btzsdzv5, running seablock 1.1, and has e.g:
- sour gas (fluid) unlocked by oil processing (technology)
- air compressors 1 (technology) unlocked by electronics (technology)

_Originally posted by @Black-Noise in https://github.com/ShadowTheAge/yafc/issues/31#issuecomment-749518188_

**Comment by ShadowTheAge** [comment]
The fact that technology were hidden were never used before. Mods have probably changed and now that research is availible but hidden.
Fixing this bug will be slightly regressive but not too bad. Will be fixed in 0.5.4
@Black-Noise

You can test the fix now by building yafc yourself, https://github.com/ShadowTheAge/yafc/blob/master/Docs/HowToBuild.md

**Comment by Black-Noise** [comment]
Does appear to be fixed, those recipes are correctly unreachable now.
