### ISSUE TITLE
[BUG] Creative Mod causes critical error

### ISSUE THREAD

**Issue by LukeMeszar** [ShadowTheAge/yafc#87]
YAFC: v0.5.3.1
Factorio: v1.1.x
Creative Mod: v1.7.1

When trying to start a project in a save that has Creative Mod enabled, a critical error occurs. 
![image](https://user-images.githubusercontent.com/10803189/103181768-2209e200-4862-11eb-931c-6dae661936b5.png)

Maybe the easiest solution would be to always treat this mod as disabled in the mod list since the items in are probably never going to be used in this tool.

**Comment by ShadowTheAge** [comment]
Thanks for the report
It should now be fixed for the next version 0.5.4

You can test the fixed version by building yafc from sources: https://github.com/ShadowTheAge/yafc/blob/master/Docs/HowToBuild.md

**Comment by ShadowTheAge** [comment]
v0.5.4 has been released as a pre-release. I am closing the issue now, if your problem is not solved feel free to reopen it.
