### ISSUE TITLE
Non-visible tabs cannot be renamed or deleted

### ISSUE THREAD

**Issue by slaneyrw** [ShadowTheAge/yafc#88]
Hi, firstly thanks for the great tool.

I'm using the Angel/Bob mods and, of course, I have a crazy amount of production sheets.  There are too many to show on the tab strip but they are available in the overflowed drop list.

I would like to rename or delete one of those production sheets in the overflow list.

It appears that functionality is only available if you either click on the tab ( to rename ) or the tab's close button respectively.  Since the tab is not visible I can't do either, nor move it into view.

Related: Can only sort visible tabs by clicking and dragging tab.  Cannot sort extra tabs.

**Comment by ShadowTheAge** [comment]
The intended way is that you can close the regular tabs (that will not delete those) and use regular tabs for the most currently interesting things while having "overflow" list for other things.

"overflow" list is sorted alphabetically and I don't want to change this, but I should add an ability to rename/delete tabs from that list.

**Comment by slaneyrw** [comment]
Thanks for the info.  What I didn't realize is the vertical scrollbar in that list, my windows theme made it almost invisible.  Now I have noticed that closed tabs are there at the bottom.  Problem solved if I close some of the tabs now I know not actually removing them completely.

**Comment by ShadowTheAge** [comment]
v0.5.4 has been released as a pre-release. You now can edit page settings using middle-mouse-click (and that info was added as a tooltip)
