### ISSUE TITLE
[BUG] Recipes not found 

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#92]
- Be sure that you are using the latest version of YAFC   yes i am 
- Please note that YAFC is my personal project and I can't promise any support!
- Specify the YAFC version   last one up as of now 53

1) TURD recipes from py are not found , the simik ore recipes
2) some mods are not discoverable at all , pymeteoritmining
3) when i add someones nuclear setup powerplant and try to add fuel i get the error i sent u on discord
NOTE it is a burner type , not a script so it shouldn t have problems but it does

**Comment by ShadowTheAge** [comment]
1 and 2 turned to be non-issues, 3 fixed in the next update (0.5.5)

**Comment by ShadowTheAge** [comment]
0.5.5 published as a pre-release
