### ISSUE TITLE
[Feature request] Increase level of verbosity on 'End of Central Directory record....' error

### ISSUE THREAD

**Issue by siorai** [ShadowTheAge/yafc#93]
- Encountered this guy and took a bit of finagling to figure out which zip file was the culprit. 
- Could be useful if the zip file in question was also returned along with the rest of the error.
- Love your work on this. Cheers

![image](https://user-images.githubusercontent.com/11640169/104263186-12d88600-5457-11eb-8613-5f0cb72c8423.png)

**Comment by ShadowTheAge** [comment]
Hi, I have added an info with which mod caused a failure if there is one. This is just one of hundreds of errors that could happen there.
The update will arrive in 0.5.5
