### ISSUE TITLE
 [BUG] lua incompatibility in Angel's Mods, regarding pairs()

### ISSUE THREAD

**Issue by suyjuris** [ShadowTheAge/yafc#98]
See Arch666Angel/mods#529.

**Comment by ShadowTheAge** [comment]
YAFC also uses custom pairs() function.
I need a new game save file for syncing mods, and exact recipe that causes problems

**Comment by suyjuris** [comment]
Oh! I definitely did not see that you use a custom lua builds in your releases. (I ran it from source, because I wanted to change some GUI things.) In this case, I would kindly ask you to mention that in your README and apologise for wasting your time.

**Comment by ShadowTheAge** [comment]
Builds run from sources uses custom lua as well. So the bug is there. Lua build is custom but it may not be the same

**Comment by suyjuris** [comment]
It definitely did not use the custom build. The story goes like this: I clone the repo and look for a way to build (I am not familiar with C#). After looking into `build.bat` and the internet, I settle on running `dotnet run` in the YAFC folder. It complains about not being able to find a `liblua52.so`. I assume this is just the usual experience of shared library madness and look potentially matching files on my system. Indeed, there is liblua5.2.so, installed by some package. So I change `"liblua52.so"` in `YafcLib.cs` to `"liblua5.2.so"` and everything works (or appears to, at least). Of course, now YAFC uses the system lua instead of its custom one.

So you maybe want to write something into the README? Also, it might make sense to give a custom error message on failing to find `liblua52.so`, or even to patch a marker variable/function into lua so that you can check at runtime that you have the right one.

**Comment by ShadowTheAge** [comment]
When I run dotnet build it copies platform-specific shared libraries from `YAFC/lib/(platform)`. You can find my lua build there.

Then you can run `YAFC` as an executable or use `dotnet YAFC.dll`

**Comment by suyjuris** [comment]
Do you always run release builds then? I can do `dotnet publish YAFC/YAFC.csproj -r linux-x64 --self-contained false -c Release -o Build/Linux` (from `build.bat`), which creates a working install in `Build/Linux`. Doing just `dotnet build` or `dotnet publish` I could not find a way to make it build a working install. In particular, I am not sure how to create a working debug build in a proper way. But getting it to work for me personally is not a problem now that I know that `liblua52.so` exists.

**Comment by ShadowTheAge** [comment]
No, when running from IDE it also correctly copies these files to the debug directory.

**Comment by ShadowTheAge** [comment]
I have rebuilt custom lua from these sources https://github.com/Rseding91/Factorio-Lua/tree/master/src
Currently windows-only. I will update osx/linux binaries in later versions.
